### ISSUE TITLE
Global Search: "Search" should be insensitive with empty entry

### ISSUE THREAD

**Issue by danrabbit** [elementary/code#1008]
## What Happened

When performing a global search, you can initiate a search with an empty search field, which highlights ever single file with hundreds of matches

## Expected Behavior

The "Search" button should be insensitive unless there is input

## Steps to Reproduce

1. Have a file open so that you can open the global search dialog
2. Search without entering any input
3. Notice that all files match hundreds of times

**Comment by danrabbit** [comment]
It looks like there is a property binding that should be handling this, but it doesn't appear to be working

**Comment by jeremypw** [comment]
Yes, there are a couple of things I thought were fixed in the PR which do not seem to work now its merged - will fix.
