### ISSUE TITLE
Projects with same name not distinguished

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1021]
## What Happened

It is not possible to add the same project twice to the sidebar, but it is possible to add a fork of a project that resides at a different path but has the same name.  It is not then possible to tell which is which.  This becomes more important in the context an "active-project" concept required by certain operations such as global search, new branch, build & run

## Expected Behavior

Where two projects have the same basename, the names should be extended to show the parent folders or otherwise make them distinguishable.  See also #34

## Platform Information

Elementary 6 daily

**Comment by igordsm** [comment]
I'll take this one as well.

**Comment by igordsm** [comment]
Some progress
![Screenshot from 2021-10-05 09-52-19](https://user-images.githubusercontent.com/221446/136026250-d8295c47-5391-49d5-b698-053e2a951cbf.png)

It uses the same algorithm as #34 . Now I'm onto getting these unique names working for the global search and project selection widgets
