### ISSUE TITLE
Move the outline to the right allowing it to be document-dependant

### ISSUE THREAD

**Issue by tintou** [elementary/code#1033]
## Problem

The left pane is not really tied to the document context, outline symbols feels out of place there

## Proposal

Move the outline symbols to the right

## Prior Art

My artistic PR: https://github.com/elementary/code/pull/377

**Comment by jeremypw** [comment]
I would suggest it be styled as (or even part of) the document view not a sidebar (like the mini-map?).

Needs to be decided what to do in response to the "Toggle sidebar" shortcut.  I would suggest it does not hide in response to that -if it is not needed the user can turn the plugin off.
