### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by fmneto** [elementary/code#1063]
I found a few spelling errors in the source code, specifically in files:

* src/FolderManager/ProjectFolderItem.vala
* src/Services/Document.vala
* plugins/terminal/terminal.vala

The attached patch contains the fixes.

[0010_fix_spelling_errors.patch.gz](https://github.com/elementary/code/files/6621155/0010_fix_spelling_errors.patch.gz)

**Comment by jeremypw** [comment]
@fmneto Thanks for the patch! I have created a PR based on your patch.
