### ISSUE TITLE
New file creation

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/code#1065]
## Problem

I don't see a way to create a new file other than using Ctrl+N outside of a project. Clicking on New File doesn't open one nor is there any option in the titlebar (unless I'm missing something).

## Proposal

Create a new file button next to the open button and open a new file when clicking on New File in the main part of the window.

**Comment by jeremypw** [comment]
This version of elementary/Code are you using?  On elementary 6 daily, the "New ... Empty File" option in the project folder context menu works as expected (note that after confirming the name the item will be sorted into a different position in the project).  Also you can create a new document using the "+" button on the notebook and then save that document where you wish.

**Comment by jeremypw** [comment]
The headerbar is already fairly crowded now we have added a Choose Project button.

**Comment by shawn1thompson** [comment]
It appears I'm using the latest version, i.e., 3.4.1. I assume by "the "New ... Empty File" option" you mean in the left pane when right-clicking on a project folder. I would think that clicking on New File or Open File would work as Open Folder does, i.e., clicking on it and something happening.
 
![Screenshot from 2021-06-10 09 05 15](https://user-images.githubusercontent.com/32218754/121539648-78f81380-c9cb-11eb-9183-9d656ccd5043.png)

**Comment by shawn1thompson** [comment]
> The headerbar is already fairly crowded now we have added a Choose Project button.

I can see this.

**Comment by jeremypw** [comment]
In the "No FIles Open" View, clicking on "New File" opens a new document - is that not what you expect or see?  I agree that "document" might be a better word than "file" in this context.

**Comment by shawn1thompson** [comment]
I wasn't trying to bring focus to choice of words :) ; rather, the only thing that works for me is the Open Folder when clicked on. New File doesn't open a new file nor does Open File open a file. They simply don't do anything when clicked on.

**Comment by jeremypw** [comment]
Hmm, I just noticed that when Code (master version) is first opened, with no projects or files restored, then single clicking on *any* of the buttons in the "No FIles" view does nothing (!) However, *double-clicking" does activate them, and if the "No Files" view is returned to, then the buttons work normally.  Weird.  Looks some kind of focus issue.  Thanks for noticing this.  I'll look into a fix.
