### ISSUE TITLE
Replace `/home/username/` with `~/` in paths

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#1068]
## Problem

We're putting paths in several tooltips now, like Notebooks and the project switcher, and maybe soon the sidebar (#1067). These get super long and repetitive, since most files are going to be within your path. 

## Proposal

We should consistently replace the user's home directory with the `~/` shorthand to cut down on the length.

## Prior Art

Atom puts the current project's path in the titlebar starting with `~/`

**Comment by jeremypw** [comment]
Yes, I considered limiting the tooltip to e.g. the last few directories and ellipsizing the rest but there is no clear number of directories that might be significant so I dropped that.  This would cut a couple of directories off.  I guess that anyone using Code for development is going to know what "~" means.

**Comment by jeremypw** [comment]
Implemented for the sidebar with #1067.  Needs implementing for project chooser and tabs.
