### ISSUE TITLE
Wrong locale code for Moldovan/Romanian

### ISSUE THREAD

**Issue by fmneto** [elementary/code#1072]
The locale being used for Moldovan language is wrong. According to ISO-639-2 the correct code is 'ro'. Or if it has to be country-specific, 'ro-MD'.

That might cause the locale to be missed by glibc, compromising localisation.

See:
https://www.loc.gov/standards/iso639-2/php/code_list.php
https://en.wikipedia.org/wiki/Moldovan_language

Possibly related: elementary/terminal#598

**Comment by jeremypw** [comment]
Closing as it appears to be fixed in master.
