### ISSUE TITLE
feature request : bring the Add-New-View F3 option (Split View) back

### ISSUE THREAD

**Issue by eric0001** [elementary/code#1080]
In elementary OS 6 Beta 2 Odin , there is no possibility to tile two elementary-Code windows side-by-side and also the Split View (Add-New-View F3) option that used to be present in elementary-Code in elementary OS 5.1.7 Hera has disappeared.
So that leaves us without any possibility to compare two text files side-by-side.
![elementary-code_add-new-view_F3_option](https://user-images.githubusercontent.com/39679934/126071729-7ca39303-293a-42f3-b76d-8ee23cad95e9.png)
![elementary-code-no-split-option](https://user-images.githubusercontent.com/39679934/126071736-178dde3a-9bed-4a9a-93a3-2bfa38572876.png)

**Comment by jeremypw** [comment]
You can tile two code windows side by side by snapping each window to opposite sides of the screen. Admittedly that takes up the whole screen but you can have any number of workspaces so its not a big problem.  The SplitView was deliberately removed so it would require a very strong argument to reverse that decision.

**Comment by eric0001** [comment]
> You can tile two code windows side by side by snapping each window to opposite sides of the screen. Admittedly that takes up the whole screen but you can have any number of workspaces so its not a big problem. The SplitView was deliberately removed so it would require a very strong argument to reverse that decision.

Thank you for the reply. Unfortunately your solution is not working on my laptop. My code window cannot be snapped to opposite side of the screen. Neither with the mouse dragging the code window to the screen side nor using the keyboard shortcut Ctrl+Super+left_key or Ctrl+Super+right_key. What am I doing wrong ?

**Comment by jeremypw** [comment]
If your screen is less than 1920px wide then there is an issue with half-screening Code at the moment (#1058).  Hopefully this will be fixed soon.  Sorry for forgetting that.  So at the moment you would have to size and arrange the two windows manually :disappointed:

**Comment by eric0001** [comment]
> If your screen is less than 1920px wide then there is an issue with half-screening Code at the moment (#1058). Hopefully this will be fixed soon. Sorry for forgetting that. So at the moment you would have to size and arrange the two windows manually

Thank you very much for your reply. You're right! :-) My screen resolution is 1366 x 768 px. That's why! It's okay. At least now I know why. I hope it will be fixed in the near future.

**Comment by jeremypw** [comment]
I have pushed a PR (#1081) that improves the situation a little but unfortunately only allows half-tiling down to 1600px screens so will not help in your case.  Getting Code to fit in a window as small as 684px would require major refactoring.

**Comment by danrabbit** [comment]
I'm going to close this as a design conflict since the split view really messes with a lot of other long-term goals and features for Code and tiling exists as a window manager feature. There is issue #1082 that tracks making sure Code can be tiled on small displays
