### ISSUE TITLE
Crashes when dragging tab over to open a new window

### ISSUE THREAD

**Issue by Deasonfun** [elementary/code#1095]
## What Happened

When I drag an open tab over to the desktop to create a new window, a new blank window opens but both crash.

## Expected Behavior

Dragging a tab over should open the file in a new window.

## Steps to Reproduce

1. Open file in a new tab
2. Drag the tab out to the desktop

## Platform Information

ElementaryOS 6

**Comment by igordsm** [comment]
I can reproduce this and might know why it breaks. On it.
