### ISSUE TITLE
Move Strip Trailing Space from the Extensions tab to Behavior or Interface

### ISSUE THREAD

**Issue by delight-aug** [elementary/code#1098]
## Problem

The so-called extensions are not really extensions but just checkboxes for a particular feature.

## Proposal

They better be proper switches in Behavior or Interface tabs.

**Comment by jeremypw** [comment]
They are extensions inasmuchas they are provided by separate modules through a plugin architecture, not by the main codebase. So, in theory at least, there could be third-party plugins in the list.

**Comment by jeremypw** [comment]
I agree that some extension functionality like "Preserve Indent" could be absorbed into the main code base as settings.

**Comment by igordsm** [comment]
I'm working on a Snippet functionality and having "Preserve Indent" (and its functions) in the main code base would be very convenient. Some of the code would be useful when inserting snippets with multiple lines. @jeremypw I could work on this refactoring, is it desirable?

**Comment by jeremypw** [comment]
@igordsm Its :+1: from me.  Maybe best to raise a specific issue first to get wider feedback in case there is a drawback I am not aware of.

**Comment by Marukesu** [comment]
I'm working in add support for the rest of the editorconfig spec, and it would be good to have "Strip trailing whitespace" as part of code itself.
