### ISSUE TITLE
Automatically open newly created file from sidebar

### ISSUE THREAD

**Issue by mcclurgm** [elementary/code#1102]
## Problem

I often create new files from the sidebar, so that they have a defined place on my disk from the start, rather than using the new tab feature. When I do this, I have to manually open the file once it's created.

## Proposal

Code should open the file when it's created.

## Prior Art

This is what GNOME Builder does. I'm not super sure about other project-based editors. I think Nova does as well, but I haven't used it in a while.

**Comment by jeremypw** [comment]
I think this was recently fixed by https://github.com/elementary/code/pull/1097?

**Comment by igordsm** [comment]
Duplicate of #1096 , which was fixed by #1097. @mcclurgm I also create files using the project sidebar and this was really bothering me. It should be fixed in the next release.

**Comment by mcclurgm** [comment]
Yep, it is. Sorry, I forgot to check closed issues!
