### ISSUE TITLE
Welcome screen does not accept dropped tabs

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1143]
### What Happened?

Attempted to move a tab to a secondary Code window with no open documents (and therefore no visible notebook) by dropping on the Welcome view.  Instead a third window opened.

Dropping a text file from Files onto the Welcome view did create a new document in that window.

### Steps to Reproduce

1. Open two Code windows one with open documents and one without.
2. Drag a tab into the empty window's Welcome view
3. Observe that a third window opens 

### Expected Behavior

Dropping a tab onto a Welcome view should behave the same as dropping a text file.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by jeremypw** [comment]
Not sure if this is easily fixable without modifying Granite.DynamicNotebook to make the underlying Gtk.Notebook more accessible.

**Comment by colinkiama** [comment]
Now that we're now using Hdy.TabView, is this now possible?

**Comment by jeremypw** [comment]
Quite possibly - I'll try and look into it soon.

**Comment by zeebok** [comment]
This issue still seems to be present in OS8 stable

**Comment by jeremypw** [comment]
There is already code in Code accepting dropped files on the welcome view and this seems to be working in Horus at least (provided you drop a text file).  As the welcome view replaces the TabView additional code is still required for it to accept dropped tabs.

**Comment by jeremypw** [comment]
Looking more into this I am not sure it is soluble because the DocumentView from which the tab was dragged creates the new window and there is no obvious way for it to know where the tab was dropped.  It just listens for  a "create window" signal from the TabView, which is a sealed class.

**Comment by jeremypw** [comment]
I am going to close this as unfixable within Code.
