### ISSUE TITLE
Significant memory leak during use

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1163]
### What Happened?

System monitor indicated the memory usage of Code (flatpak) on start up was around 30Mb.  After using for development for a while I noticed the memory usage was approaching 1Gb.  The only extension activated was "Outline".  Autosave was on.

### Steps to Reproduce

1. Start Code and note memory use
2. Use intensively for a while
3. Note memory use

### Expected Behavior

Memory usage should only increase moderately and should mostly be recovered when documents and projects are closed.

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by jeremypw** [comment]
Seems to be caused by a combination of the autosave behaviour and the outline plug which causes megabytes of memory loss for every character entered (!) once it starts happening.  Both things need to be active for it to start but once it starts happening disabling either of these behaviours does not stop it however.

**Comment by kaixoo** [comment]
This should be at least priority high

**Comment by jeremypw** [comment]
Needs checking whether it still happens.

**Comment by kaixoo** [comment]
I can reproduce. With all extensions enabled, Code is not letting me type a single letter and crashing. I'll send a log later

**Comment by jeremypw** [comment]
Thanks! Remember to include system details.

**Comment by jeremypw** [comment]
Strictly speaking, the issue related to Autosave + Outline - was that reproduced.  If it can be narrowed down to particular plugin(s) it will be easier to fix.

**Comment by kaixoo** [comment]
Oop! The issue was because of the vim plugin :facepalm: I can't reproduce, but you should try too.

**Comment by jeremypw** [comment]
The Outline plugin has been rewritten into the main code since this issue was raised so I don't think it is valid any more.

I'll have a look at the Vim plugin ('though I never use it).

**Comment by jeremypw** [comment]
Very limited testing of the Vim extension did not reveal any issues.  No obvious sources of significant leaks seen in the code.   I'll close this now - it can be reopened or a new issue opened if a reproducible memory leak can be identified.

**Comment by kaixoo** [comment]
Sorry for the confusion. The vim extension didn't have any issues, just my stupidity.

Does it even make sense to maintain a Vim plugin for a low-maintained tool that's supposed to be minimal? I can understand some people prefer Vim workflow but at that point, just use Vim directly is a better approach

**Comment by jeremypw** [comment]
Well, its been there since about 2013 and saw some development in 2018-2021 so at least a couple of people thought it useful enough to make an effort.  Although I personally don't see much use for it I am reluctant to remove it unless it is causing serious problems.  It does appear unfinished - the VISUAL mode is unimplemented and it only implements a subset of other commands.
