### ISSUE TITLE
Dragging New Document tab opens two identical tabs in a new window

### ISSUE THREAD

**Issue by joeljosedev** [elementary/code#1168]
### What Happened?

When a New Document tab is dragged from its current position, two copies of it are opened in a new window and the one in the old window is closed. This issue does not appear for files that are saved on disk.

https://user-images.githubusercontent.com/53969297/149732482-5d122b9e-77e3-4697-a81d-9f85b6bcccb6.mp4

### Steps to Reproduce

1. Open Code
2. Click on `New File`.
3.  Enter some text.
4. Drag the tab and move it from its current location.
5. Observe that two copies of the document are open in the new window.

### Expected Behavior

No copies of the New Document must open in the new window.

### OS Version

6.1 (Jólnir)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
This seems fixed in the latest version. Feel free to reopen if recurs.
