### ISSUE TITLE
Autosave of unsaved buffers not reliable

### ISSUE THREAD

**Issue by davidak** [elementary/code#1183]
### What Happened?

https://youtu.be/LrOn42Y4aIE

This works with other editors like Atom and Sublime Text. It is an essential feature for me!

### Steps to Reproduce

1. Open Code
2. New File
3. Type "something"
4. Close Code
5. Open Code

### Expected Behavior

The typed text should be saved.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

**Comment by vjr** [comment]
Just a guess that autosave triggers after a short delay of no typing so if app closed soon after typing something that last typed content doesn't get saved. Fix would likely be to trigger any unsaved content explicitly on close document if the option is enabled?

**Comment by vjr** [comment]
I am able to repro this issue - autosave works if you close just the tab - does not work if you either quickly click the X close button after typing fresh text or press the CTRL+Q quit shortcut.

Looking into a fix.

**Comment by jeremypw** [comment]
@davidak If you are able to test out https://github.com/elementary/code/pull/1188  that would be helpful :smile:
