### ISSUE TITLE
Drag and drop of selected text not working with accented characters

### ISSUE THREAD

**Issue by leodom** [elementary/code#1191]
### What Happened?

Drag and drog of accented characters transforms them into their unicode equivalent

For example, **légèreté**  turns into **l\u00e9g\u00e8ret\u00e9** 

### Steps to Reproduce

1 - Select text with accented characters
2 - Drag selected text to other location within document
3 - after dropping text, accented characters are converted to their unicode

### Expected Behavior

words to be moved 'as is'

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

This has been happening on other computers and older OS versions...

**Comment by jeremypw** [comment]
Occurs when dropping within Code and into Code from other app.  Attempt to drag accented characters into another app *from* Code failed so presumably its the selected data that is in the wrong format.
