### ISSUE TITLE
Code not respecting system theme

### ISSUE THREAD

**Issue by selwynorren** [elementary/code#1268]
### What Happened?

After installing Elementary OS 7 and selecting the dark theme. I opened code only to find that it is using teh light theme, despite the option being selected to Follow System theme.

If I switch off the Follow System Theme toggle I am presented with 3 Circles, All three of them are white with no variations between them, Selecting the circle on the right changed the theme to dark, however if I activate the Follow system them again, nothing happens. It does not matter which variation I select or toggle teh Follow System theme, only clicking the right had white circle does any changes

### Steps to Reproduce

As descibed above

### Expected Behavior

Code should automaticlly follow system theme
Fox colour selection options

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Using nVidia 390 driver

**Comment by danirabbit** [comment]
Thanks for your report. Can you post a screenshot showing the issue? Have you perhaps changed or modified your system stylesheet?

**Comment by selwynorren** [comment]
Hi danrabit, sorry was traveling for a bit, here are the screenshots.

In this first image you will see that my system settings have been set to dark mode
![image](https://user-images.githubusercontent.com/570607/220037183-27ce4150-e191-40ce-8e84-eeba3e1990d5.png)

In the next screenshot, you will see the first launch of Code and its not following system settings for dark mode.
![image](https://user-images.githubusercontent.com/570607/220037478-b3f5d547-c14e-4a38-b670-745acb4f9d92.png)

This next screenshot show if I click the gear icon for settings. The setting to activate follow style setting is active but ignored. 
![image](https://user-images.githubusercontent.com/570607/220037579-76607a61-c9be-407c-bef4-b59bb641e813.png)

This last screenshot also show that the light theme has been set when I deactivate follow system style. You will also notice that my three circle options all show exactly the same.
![image](https://user-images.githubusercontent.com/570607/220037926-cace7573-0bfc-440d-93d9-b587bf6dde6e.png)

If I manually select dark mode, then it all works just fine
![image](https://user-images.githubusercontent.com/570607/220037987-ea65505e-9fba-473e-8772-af46df01f72d.png)

**Comment by jeremypw** [comment]
#1270 Just merged which fixes the problems with following system style when no docs are open.  However, the screenshots show non-standard window decorations so this does not appear to be a standard native Horus install, which may mean there are issues with the stylesheet.

**Comment by danirabbit** [comment]
Yeah this looks like a much older version of the elementary stylesheet actually. So, OP this is definitely due to your modifications. Closing since this issue would be fixed by using the default system stylesheet

**Comment by selwynorren** [comment]
Thanks, just incidentally, the style sheet issue resolved the reason why the 3 circles were showing as the same color, However, boot form a live USB shows the theme colours correctly, but its still not following the dark theme settings.

I will reinstall the OS later today and see if that resolves teh app not following the default theme style

**Comment by jeremypw** [comment]
@selwynorren Note that although the fix is merged into the master branch it will not be released to the stable build for a while. We try and make a stable release about once a month.

**Comment by selwynorren** [comment]
> @selwynorren Note that although the fix is merged into the master branch it will not be released to the stable build for a while. We try and make a stable release about once a month.

Thanks so much, I initially read it wrong and though the comment meant the style also affected the functionality, but I understand now. Thanks so much for all your work you guys do, really appreciative of your efforts

Please advise me where do I report a bug installing firefox (Well more of a comment/question than a bug)

**Comment by jeremypw** [comment]
@selwynorren It depends rather on the nature of the comment/question but you try asking on the Slack or Reddit community channels initially. You can join the Slack community at https://elementarycommunity.slack.com/signup#/domain-signup

**Comment by selwynorren** [comment]
Thanks so much, I have posted in slack
