### ISSUE TITLE
Some way to use dark mode

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#127]
I've been thinking about this a lot and I really think we should offer some method of using the dark stylesheet in Scratch. Every code editor I can think of offers a dark theme, and almost everyone I see using a code editor is using a dark theme.

I personally have resorted to using the Inspector to toggle it on at the beginning of my session because staring at a bright UI all day hurts my head, but that's a pretty hacky solution :stuck_out_tongue:

I know back in the day someone wrote a patch to automatically request the dark theme if "Dark" appeared in the syntax theme name, but that wasn't very smart (i.e. it didn't work on dark syntax themes like "Oblivion"). An alternative would be to just carry a list of dark/light syntax themes and toggle the stylesheet based on that, but at that point I think it might just be better to have a dark mode toggle.

**Comment by cassidyjames** [comment]
It looks like Launchpad bugs did not all get imported. This was reported as [bug 1469166](https://bugs.launchpad.net/scratch/+bug/1469166) as a regression to [bug 1269593](https://bugs.launchpad.net/scratch/+bug/1269593)

**Comment by cassidyjames** [comment]
After a short discussion with @elementary/ux, I think the way forward on this is to change the "Color scheme" dropdown in the preferences to a light/dark mode toggle that changes both the color scheme (Solarized Light/Dark) and the GTK mode.

Design-wise, Dan likes the circle-shaped color buttons, kind of like [this screenshot](https://user-images.githubusercontent.com/611168/27648395-a6be2c3e-5beb-11e7-8ea7-302b6232a019.jpg). I imagine they'd be the solarized light and dark backgrounds, and we'd have to make sure it's clear which is selected.

**Comment by Nine-H** [comment]
it'd be nice if the app/granite did something clever using the background color of gtksourceview, I'm not keen on solutions that enforce the use of solarized because I really like monokai.

**Comment by ChristopherNugent** [comment]
While I agree that simplifying the UI would look good and be pretty convenient, I don't think it's worth giving up the choice of more color schemes. What if the app allowed the user to select their own light and dark themes (default of the two Solarized themes), and switch between them via the simpler selector?

**Comment by aleksandar-stefanovic** [comment]
I think symbolic versions of the icons look better when dark theme is applied, because they're monochromatic fade into the background nicely, which should be a priority when it comes to a professional tools like IDE's, where the focus should be on the code, rather than surrounding options (IMO).

Also, are there any conclusions on this issue? Would creating a simple option to toggle light/dark theme be a good place to start?

**Comment by cassidyjames** [comment]
@aleksandar-stefanovic I think that'd be a consideration for the dark variant of the stylesheet altogether versus an app-by-app basis, but I'm not sure. I think it's out of the scope of this change regardless.
