### ISSUE TITLE
Code does not follow system theme when launching with no files open.

### ISSUE THREAD

**Issue by MobileAZN** [elementary/code#1270]
### What Happened?

When launching Code with no files open and 'Follow System Style' selected, it defaults to the light theme regardless of what the system theme is currently set to then changes once a file is opened.  When a theme is chosen (Classic, elementary Light, elementary Dark), it follows that setting correctly on startup.  This is only when 'Follow System Style' is enabled.

Once a file is opened, the theme then switches properly.

This is not the same as [Issue 1268](https://github.com/elementary/code/issues/1268)

### Steps to Reproduce

1. Open Code
2. Enable 'Follow System Style'
3. Close Code
4. Wait for night to fall
5. Open Code
6. Burn your retinas (Code opens in elementary Light style)

### Expected Behavior

I expect Code to launch in elementary Dark when 'Follow System Style' is enabled in Code and the System Desktop Style is Scheduled (mine is currently Sunset to Sunrise).

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Lenovo ThinkCentre m900 Tiny
Quad-Core Intel® Core(TM) i5-6600T CPU @ 2.70GHz
Intel® HD Graphics 530
16 GB memory
756 GB storage (512GB NVME, 256GB SSD)

Nothing special

**Comment by MobileAZN** [comment]
@jeremypw It's nice to know what I was thinking and where I was looking was the correct area (SourceView/MainWindow), even though I don't know vala well.  I grok'd the PR, but wouldn't have been able to do that myself yet.  Thanks!

**Comment by selwynorren** [comment]
Howdy whups yeah I actually forgot about that, I did have pantheon tweaks installed and am using elementary X theme install in my home directly
