### ISSUE TITLE
Markdown highlighting is incorrect for double nested lists

### ISSUE THREAD

**Issue by CyriacBr** [elementary/code#1279]
### What Happened?

As you can see here:  
![image](https://user-images.githubusercontent.com/38442110/222681525-56c83bc0-3af3-45d0-81bb-7f563961ff56.png)

### Steps to Reproduce

Open Code, select `Markdown` as the header of the app and write this:
```md
Markdown Test
Blah balh
    - Test
        - Nested test
        - What is this whole line in blue?
    
```

### Expected Behavior

Deep nested lists should not be highlighted in blue.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Hardware Info

My linux is ubuntu with Phanteon DE.
My display drivers:  
![image](https://user-images.githubusercontent.com/38442110/222682634-f18c67c6-1789-44af-a7f8-fd8f8406c4bc.png)

**Comment by tintou** [comment]
Hi there, we are using `gtksourceview` to render the text, you can test with the latest version in GNOME Builder that your bug is still present and report the issue upstream at https://gitlab.gnome.org/GNOME/gtksourceview so that everyone can benefit from the improvements :slightly_smiling_face:

**Comment by tintou** [comment]
Closing as it has to be reported upstream. Thanks for this.

**Comment by CyriacBr** [comment]
Will do, thanks!
