### ISSUE TITLE
Cannot open files with unknown characters

### ISSUE THREAD

**Issue by TomiOhl** [elementary/code#1282]
### What Happened?

Code cannot open files that contain unknown characters.
I've tried to open .bash_history, which contained some of these for some unkown reason (corrupted save?), but it only displays an error message saying the file cannot be read or is corrupted.

### Steps to Reproduce

Try to open this file: [invalid_test.txt](https://github.com/elementary/code/files/10957534/invalid_test.txt)

### Expected Behavior

The file should open normally. Possibly indicate that there are weird characters

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
LibreOffice Writer could neither open nor repair the example file either ...

**Comment by jeremypw** [comment]
It seems Gtk.SourceFileLoader does in fact load non-text files (although not in a very helpful form) so it would be possible to give the user to show non-text content. This is what the example file shows (after manual insertion of some new line characters to reduce the line length) when load errors are ignored:
![Screenshot from 2023-03-15 10 03 58](https://user-images.githubusercontent.com/10513844/225276946-2f079a7a-4650-4b03-a014-ef4dfbdc0d39.png)

A complication is if autosave is "ON" then the original file will be likely to overwritten and lost. So the solution will have to create a new document containing the mangled text and leave the original file as it was.

I still think it is outside the scope of Code to try to repair such files.

**Comment by jeremypw** [comment]
@TomiOhl I have pushed a draft PR providing a fix for this issue.  Note however, the design team may not agree that this should be merged.

**Comment by TomiOhl** [comment]
Thanks! Hope they accept it, or in the worst case I'll have an official explanation why couldn't this be handled.
