### ISSUE TITLE
VSCode integration into Code

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/code#1292]
### Problem

I am a very geeky person and I love Linux, but specially elementary OS. I feel it's the only Linux distribution that feels like an actual OS.

Code is amazing, but I often find myself locked into VSCode for the amazing language support it provides.

And that's bad because it breaks the aesthetics

### Proposal

I am investigating on a vendor neutral VSCode extension host. It's not an easy process, but I think it would be super useful for many projects like this. Already made a proposal on CodeEdit and they didn't reject it. Would Code extension API allow this? The idea is that the extension host would run in a normal Code extension

**Comment by jeremypw** [comment]
Some attempts were made to integrate GVls into Code using a plugin. (see  https://github.com/elementary/code/pull/1062 and https://github.com/elementary/code/pull/1132) and although there was some success there were issues with performance and amount of extra code needed.  I haven't looked into VSCode but, in principal, a language completion plugin is possible.  We would be willing to make (limited) changes to the plugin API to support this if necessary.

**Comment by aitor-gomila** [comment]
Great thing. Don't intend to support everything VSCode offers, but maybe things like LSP would be great. Are plugins able to display custom GUI elements?

**Comment by jeremypw** [comment]
@aitor-gomila Yes, plugins can connect to these interface signals:
```
        public signal void hook_window (Scratch.MainWindow window);
        public signal void hook_share_menu (Gtk.Menu menu);
        public signal void hook_toolbar (Scratch.HeaderBar toolbar);
        public signal void hook_document (Scratch.Services.Document doc);
        public signal void hook_preferences_dialog (Scratch.Dialogs.Preferences dialog);
```

so they have access to the main UI elements and therefore to their public components and signals.

**Comment by aitor-gomila** [comment]
How is it done though? GTK isn't multithreaded. Do you run plugins in the same process as Code?

**Comment by aitor-gomila** [comment]
Closing as out-of-scope...May re-open later
