### ISSUE TITLE
Drop "Draw Spaces: Never" preference

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#131]
Now that we have the awesome automagic show-on-highlight default, I don't see a lot of value in carrying a preference to toggle to other largely inferior modes.

**Comment by tintou** [comment]
I'm completely against it, I use the "always" setting and I'm happy with it, people should always be aware that they are using space or tabs.

**Comment by danrabbit** [comment]
I personally use the new highlight setting, but I can see how this might be something more personal. Something to ask maybe is if anyone is using the "never" option. If they aren't at least we could remove that and just have "always" and "smart"

**Comment by tintou** [comment]
"smart" being "on selection", nothing that smart ;)

**Comment by cassidyjames** [comment]
Since we can't come to a consensus for dropping this entirely, I'm repurposing for dropping the "Never" option.
