### ISSUE TITLE
Drop "Highlight current line" preference

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#132]
...and default to on.

It's such a subtle feature that I think having it always on would be useful for those who like it, and entirely ignorable for those who don't.

Up for discussion, though.

**Comment by danrabbit** [comment]
I'd be interested in doing this in two stages: default to "on" and see if anyone complains and then drop the preference after a bit of time.

**Comment by yeboahnanaosei** [comment]
Default to on but allow the user to be able to turn it off. Sounds fair to me

**Comment by vivekrajr** [comment]
Can this be closed? #142 was merged last July and #143 was blocked to trial #142 for some time.

**Comment by cassidyjames** [comment]
@vivekrajr probably, but there was no discussion from @tintou or @danrabbit on the PR so I'm not sure why it was closed. I'd like to know what the thinking and decision was before closing this and losing it. Are we keeping the preference because people complained? I don't personally remember hearing any feedback about it one way or the other.
