### ISSUE TITLE
Man page contains unwanted option

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1322]
### What Happened?

The man page for Code was seen to contain the option `-s, --set=plugin           Set of plug-ins` but the code does nothing with this option (although still treats it as valid).

### Steps to Reproduce

1. Open terminal 
2. Run `man io.elementary.code`
3. Compare with code in `Application.vala`

### Expected Behavior

The man page should only show options that work.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Probably not 😅

**Comment by Marukesu** [comment]
actually, the option is passed by the MainWindow class to the PluginManager, so it's used. it's a folder name that contains extra plugins (see the creation code in PluginManager.vala). if there's already a running instance, the set defined in that instance is the one used.

i don't think it makes sense in keeping it, even with a plugin system. this option could only make sense if every window was a process by itself.

**Comment by jeremypw** [comment]
@Marukesu Yes, the issue was badly worded. The use of custom plugin sets in a subfolder of `plugins` is unused and not officially supported by elementary even though the code does support it.   I agree that there is no reason not to remove this feature and simplify the code.

**Comment by jeremypw** [comment]
CLosing as fixed
