### ISSUE TITLE
Cannot rename folders from Code

### ISSUE THREAD

**Issue by SyedUmairCodes** [elementary/code#1328]
### What Happened?

I cannot rename any folders from within the Code application which is the default text editor in Elementary OS. Files can easily be renamed from within the application.

### Steps to Reproduce

1. Open a folder inside the Code (default editor) text editor
2. Try to rename the folder
3. Nothing will happen.

### Expected Behavior

The folder should be easily be able to be renamed and then the new name can be saved.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Hardware Info

Processor: Intel Core i5-4200m
Graphics: Intel HD 4600
RAM: 16GB
SSD: 256GB

**Comment by jeremypw** [comment]
Seems this is because folders are non-selectable (because they do not represent a document).  I'll see if I can fix this.

**Comment by jeremypw** [comment]
Unfortunately this cannot be fixed without reintroducing a different issue (#408) whilst the Sidebar uses Granite.Widgets.SourceList.  That widget is going away in Granite 7 so the sidebar will have to be rewritten anyway and this issue can hopefully be fixed then.

**Comment by colinkiama** [comment]
Fixed in #1386
