### ISSUE TITLE
Symbol pane changes size after reopening code

### ISSUE THREAD

**Issue by Oowoosh0** [elementary/code#1329]
### What Happened?

When closing Code with the Symbol Outline pane showing and then reopening it the Symbol Outline pane has increased in size, filling over halve of the editor window.

Window before closing:
![image](https://github.com/elementary/code/assets/3541526/ad2bd889-d552-4a3f-89b8-2b353350df14)

Window after reopening:
![image](https://github.com/elementary/code/assets/3541526/360b74c9-a2f8-4de2-9013-89c639189b56)

This only affects the last opened vala file. For all of the other vala files the size of the Symbol Outline pane actually decreases.
Window after reopening (other vala files):
![image](https://github.com/elementary/code/assets/3541526/d7b6b79a-6b89-4786-a037-e9648e92d766)

### Steps to Reproduce

1. Open a vala file in Code and open the right hand Symbol Outline pane.
2. Close Code.
3. Reopen Code and the Symbol Outline pane has increased in size.

### Expected Behavior

The Symbol Outline pane should consistently keep its size even after closing and reopening code. You should not have to resize it for every file after reopening code because it is now either to large or to small.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I can confirm that the the symbol pane width of the last opened tab is anomalous but for me it decreases in size.  I tested this by closing and reopening the symbol panes so that they all started with the default width. Then closed and reopened Code.

**Comment by Oowoosh0** [comment]
could we save the width of the symbol pane in the "saved-state" gschema and then restore it from there when opening Code? Or just use the default width when opening Code?

One downside of that would be that it would set the symbol panes for all files to the same size while they could have been at different sizes when closing Code. But to avoid that one would need to save the width of the symbol pane for each opened file separately and that seems a little excessive.

**Comment by Oowoosh0** [comment]
I can try to fix this and submit a pull request.
