### ISSUE TITLE
Search entry reverts to previous term after editing and `<Ctrl>f`

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1335]
### What Happened?

The search term reverts to its previous text if it is edited and the search repeated.

### Steps to Reproduce

1. Open a document, press `<Ctrl>f` and enter a search term
2. Press `<Ctrl>f` to perform the search
3. Edit the search term in the entry and press `<Ctrl>f` again
4. Instead of searching for the amended term, the previous term reappears and searched upon.

### Expected Behavior

The search is always performed with the current search entry text.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by zeebok** [comment]
I am actually not able to repro this. After putting in a search term, `<Ctrl>f` doesn't do anything as the search bar is open and a match is already highlighted and "selected"

**Comment by jeremypw** [comment]
@zeebok Thanks for trying this.  Looks like this only happens if "search next" has been performed at least once.  So the steps to reproduce immediately after launching are:

1. Open a document, press <Ctrl>f and enter a search term
2. Press `<Ctrl>f` to perform the search
3. Press `<Ctrl>g` to search next
4. Edit the search term in the entry and press <Ctrl>f again
Instead of searching for the amended term, the previous term reappears and searched upon.
