### ISSUE TITLE
Switching files when already selected

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/code#1337]
### What Happened?

Selecting files that are already selected in blue doesn't open the files.

### Steps to Reproduce

1. Open 2 projects.
2. Open a file of project A.
3. Open a file of project B.
4. Switch back to the file of project A using the tree view.
5. File does not open; you need to select another file, and select the original file back.

### Expected Behavior

You should be able to switch files from the tree view like in every IDE.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by aitor-gomila** [comment]
Can't reproduce anymore. Will try and see if I can reproduce it again.

**Comment by jeremypw** [comment]
I think this is related to #1319. A fix for this is awaiting review.
