### ISSUE TITLE
Add ability to drag folders to Code

### ISSUE THREAD

**Issue by ghost** [elementary/code#1338]
### Problem

It seems odd to me that you can't drag in folders in order to open them, or (optionally and debatable) drag them out to open in file explorer / close them, given how well integrated Code is in Elementary.

### Proposal

Add ability to drag folders to Code file explorer, with visual feedback like VScode.

**Comment by aitor-gomila** [comment]
You're a beast :fire:

**Comment by jeremypw** [comment]
The linked PR only implements dragging folders into Code - the other issue mentioned of dragging folders out of Code will have to be raised as a separate issue and fixed separately.
