### ISSUE TITLE
Tab width menu at the top doesn´t work

### ISSUE THREAD

**Issue by emiellr** [elementary/code#1340]
### What Happened?

When trying to change the tab width using the quick menu at the top of the window, it won't change the tab width. The +- menu will change, but the label won't and the actual tab width doesn't change either. It can only be changed in the preferences menu.

### Steps to Reproduce

1. Fresh install on Elementary OS 7 Horus
2. Open Code.
3. Default tab width will be 4 spaces. You cannot change this using the quick menu at the top.

### Expected Behavior

Changing the tab width according to the new setting.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
n/a
```

### Hardware Info

Lenovo C340 14-IWL
i3-8145u
8GB Ram
128GB SSD

Elementary OS freshly installed using mutschler.dev's install guide for eOS 6.1

**Comment by jeremypw** [comment]
There are potentially three things setting the tab width - the global preferences menu, the format bar in the header and any `.editorconfig` file in the project folder.  At the moment these are not being properly synced.  For the moment you should use the global preferences menu to set the default tab settings.
