### ISSUE TITLE
Line numbers are messed up

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/code#1341]
### What Happened?

I noticed errors in my code pointed to, e.g. `45:20`, however when focusing on that in Code, I got to the second digit in the variable/method/function.

### Steps to Reproduce

1. Get an error from a compiler with a line number
2. Go there
3. See error.

### Expected Behavior

First line in a row should be `X:1`, not, `X:0`. In practice, this means doing `+1` in GtkSourceView or Code.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
I agree that column numbers should match those given by the compiler.
