### ISSUE TITLE
A backup file remains after closing a document that has trailing spaces

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1343]
### What Happened?

A large document (3000+ lines) was edited so that it contained trailing spaces.  On closing the document it was noticed that there was an unneeded backup file remaining in the directory where the document resides.  This did not happen if there were no trailing spaces nor if the document was small (1 line).

### Steps to Reproduce

* Create or load a text document with 3000+ lines
* In Preferences make sure "Strip trailing whitespace" and "Save files when changed" are ON.
* Edit the document so that it has trailing whitespace
* Close the document
* Observe the parent folder of the document with Files and see persisting backup file.

### Expected Behavior

When a document is closed all temporary files created during editing are deleted.

### OS Version

7.x (Horus)

### Software Version

Compiled from source

**Comment by colinkiama** [comment]
I've tried to reproduce the issue. There are 2 things I've noticed:
1. The 3000+ line documents I've tried do not strip trailing whitespace at all
2. I do notice the backup file persisting after closing the document, when I check the files app however when i refresh the files app, the backup file is gone. (Could the backup file just be taking a little while to be deleted?)
