### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [elementary/code#1362]
### What Happened?

https://l10n.elementary.io/projects/code/#information is
GPLv3-only, vs.
https://github.com/search?q=repo%3Aelementary%2Fcode%20any%20later&type=code

### Steps to Reproduce

1. Translations are GPLv3-only,
2. Software is specifically GPLv3-or-later

### Expected Behavior

Everything should be GPLv3-or-later.

(Don't agree to be bound by the link to the textfile, and never did.)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Fixed! Thanks for your attention to detail
