### ISSUE TITLE
Keep tab header visible and legible

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1363]
### Problem

With a lot of documents open it soon becomes impossible to decipher the tab ellipsized labels and some may have scrolled out of view anyway.

### Proposal

One solution to this would be to have the tab headers in a FlowBox (or similar) widget so that they are always visible and legible, at the cost of consuming more height.

Another thing that might help would be to allow the tabs to arranged vertically, at the cost of consuming more width.

**Comment by danirabbit** [comment]
We should probably be porting this to Hdy.TabBar instead in preparation for Gtk4

**Comment by jeremypw** [comment]
Does that solve the issue?

**Comment by danirabbit** [comment]
Possibly, but either way it's probably not worth investing in a solution that will have to be thrown out immediately when porting to Gtk4 in the near future

**Comment by jeremypw** [comment]
The Hdy.TabBar used currently in Files does not ellipsize the labels but truncates the tab bar when the window is too narrow and makes it scrollable which keeps tabs legible but not always visible, which is an improvement but not a complete fix. 

I close this for now and raise again after Gtk4 port if appropriate.
