### ISSUE TITLE
System theme change not fully respected if Code already running

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1364]
### What Happened?

When the system theme variant changed from light to dark (or vice versa) automatically due to time or manually through System Settings/Appearance while Code was in use with "Follow System Style" ON, then the interface was left with a mixed appearance:

![Screenshot from 2023-08-09 10 42 07](https://github.com/elementary/code/assets/10513844/80a9ac24-b28c-4c30-ac38-30ad22ad05e7)

Closing and reopening Code resulted in the correct appearance.

### Steps to Reproduce

1. Open Code and turn "Follow System Style" ON.
2. Open at least one document
3. Using System Settings/Appearance toggle the system style between "default" and "dark".
4. Observe that not all parts of Code respect the change.

### Expected Behavior

Code should fully respect the change in system style while running.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by janxkoci** [comment]
I still see this whenever I open laptop in the morning if Code was opened with the dark theme in the evening the day before. No such problem if the theme switches while I use the laptop (e.g. in the afternoons/evenings), only when the theme changes after waking up from suspend. I can show a screenshot tomorrow morning, if I don't forget...
