### ISSUE TITLE
Add option to adjust fuzzy search behaviour in project file search

### ISSUE THREAD

**Issue by colinkiama** [elementary/code#1398]
### Problem

The current behaviour of the project file search can help you search for files to switch to really quickly (as long as you know the first character of the file name you are looking for).

It would be great to have some flexibility to do things like:
- Searching across path directory separators in file paths
- Being able to get search results even if file names and directory names don't have matching first characters

### Proposal

Options should be added in one of the app's menus or in the project file "Find project files" popover to adjust the way the fuzzy search behaves.

**Comment by jeremypw** [comment]
> Searching across path directory separators in file paths
Could you give an example where this would be useful when the search term does not contain a directory separator?  You can  already search across directory separators at the moment provided you include a directory separator in your search term

> Being able to get search results even if file names and directory names don't have matching first characters

I do not think filename matches require a first character match at the moment (I'll check this).  A directory match is stricter admittedly - it may be possible to optionally relax that.

**Comment by colinkiama** [comment]
> Could you give an example where this would be useful when the search term does not contain a directory separator? You can already search across directory separators at the moment provided you include a directory separator in your search term

Larger projects with deep directory structures. For example a large JavaScript project with module exports from index.js files.

**Comment by colinkiama** [comment]
> Larger projects with deep directory structures. For example a large JavaScript project with module exports from index.js files.

Actually never mind, I've been using the recent update to the fuzzy search algorithm for a bit now. This isn't an issue.

My main problem was with the filename initially requiring a first character match. Now that has been fixed, I don't think the old behaviour is needed anymore.

**Comment by jeremypw** [comment]
Thanks @colinkiama I do not think the feature is perfect yet but in practice I have already found it very useful and not had any problem finding what I want.
