### ISSUE TITLE
Sidebar: First select fails to open document after branch change which removes a sidebar item

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1403]
### What Happened?

After changing branches (which causes some of the loaded documents to change, selecting another document in the foldermanager failed to open it.

### Steps to Reproduce

1. Open a git project
2. Prepare (if necessary) a branch that contains a file not existing in another branch and switch to that branch
3. Change the branch so that the file is removed from the sidebar
4. Try to open another doc from the sidebar.

An easier way to demonstrate the problem is to create a temporary file item in the sidebar and then delete it.  The next select then fails to open a document.

### Expected Behavior

Selecting a document in the sidebar should open it under these circumstances

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by zeebok** [comment]
When I change branches on OS8 stable, it does not change what docs are open so I can't reproduce. In fact the radio button doesn't even update:
![image](https://github.com/user-attachments/assets/d0f5b137-2ccc-45f4-a72e-075510b3ad26)

**Comment by jeremypw** [comment]
@zeebok Thanks for having a look at this. Changing branches does not usually change which docs are open but may change their contents.  The issue is about opening another document from the sidebar after changing branch.  I'll rewrite the steps to reproduce.

 I can confirm the issue about which branch is selected in the Branch context menu on OS8 but this also occurs in `master` so will have to be fixed in a separate PR.

**Comment by jeremypw** [comment]
@zeebok I have revised the instructions.  It seems a bit of a corner case but this was happening to me annoyingly often during development so there may be another way of triggering it.
