### ISSUE TITLE
[Arch] New document is not a text file?

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1412]
### Discussed in https://github.com/elementary/code/discussions/1411

<div type='discussions-op-text'>

<sup>Originally posted by **HubKing** January 20, 2024</sup>
I installed it from Arch etc repository. Whenever I create a new tab, I see this thing below. If I click "Load anyway", it shows the document fine. Why do I see this?

![image](https://github.com/elementary/code/assets/10900489/20c7201f-28f7-46f7-9533-1bc51e0df613)
</div>

**Comment by ryonakano** [comment]
I'm facing this issue with the sipped version in Early Access 8:

![Screenshot from 2024-06-11 06-57-15](https://github.com/elementary/code/assets/26003928/03cc7aac-1bec-4aa2-8e80-f7842e62f412)

```
user@VirtualBox-17958d80:~$ LANG=C apt-cache policy io.elementary.code 
io.elementary.code:
  Installed: 7.2.0~r5026+pkg154~daily~ubuntu8.1
  Candidate: 7.2.0~r5026+pkg154~daily~ubuntu8.1
  Version table:
 *** 7.2.0~r5026+pkg154~daily~ubuntu8.1 500
        500 https://ppa.launchpadcontent.net/elementary-os/daily/ubuntu noble/main amd64 Packages
        100 /var/lib/dpkg/status
user@VirtualBox-17958d80:~$ 
```

**Comment by jeremypw** [comment]
This is caused by Glib now returning `application/x-zerosize` as the mime-type of empty files instead of `text/plain`.  Code needs to be modified to account for this.
