### ISSUE TITLE
Darker editor theme option/s

### ISSUE THREAD

**Issue by awsdert** [elementary/code#1430]
### Problem

While the UI can be re-themed the actual file section is stuck with a horrendously bright theme. During daylight this is not too much of an issue but at night it is a pain on the eyes. I personally prefer darker themes always so would much like some darker options.

### Proposal

I suggest implementing support for these themes:

https://github.com/rainglow/atom/tree/master/themes

That would give your users plenty of options regarding syntax highlighting themes, the current theme can be left as hard coded default or something.

**Comment by jeremypw** [comment]
Which part do you mean by "actual file section"? Maybe post a picture? For me the sidebars and everything else honor the dark theme setting as far as the background is concerned. Or is it the text that is too bright?

**Comment by awsdert** [comment]
Yeah the text in the editor itself is too bright, not the UI. I know everyone has their own preferences and inventing a whole new code syntax style format would be a pain in the ass which is why I suggested supporting an existing code syntax style format.

**Comment by zeebok** [comment]
By default the dark theme text area should look like this:

![Screenshot from 2024-04-24 22 12 38](https://github.com/elementary/code/assets/1378344/482b9620-91ab-4f9e-b0a9-13d4cad3d217)

@jeremypw can something like an editorconfig override the color of the theme?

**Comment by awsdert** [comment]
Ah, turns out the "Follow system style" didn't apply to the UI but the editor huh? I totally though it applied to the UI because I didn't expect the system to have a theme for code syntax in the 1st place. In that case my bad. This is what I got when I had left it as system theme:

![CodeSystemResult](https://github.com/elementary/code/assets/7422982/3ec95274-69d0-4f05-b01a-277538210ee7)

Since I had made an incorrect assumption I'll close this issue with this comment.

**Comment by jeremypw** [comment]
@zeebok I don't think editorconfig is intended to influence theming - see https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties for current and proposed properties.

@awsdert I cannot get the text area and UI theming to conflict as shown in your screenshot - they are either both dark or both bright.  I am using the default elementary system theming (OS7.1).  I notice from your screenshot that you have different theming installed (as judged by the icons) so I do not know whether this is causing the problem.
