### ISSUE TITLE
Opening folders with same name and on different partitions as projects causes Code to crash

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#1440]
### What Happened?

Attempted to open two versions of a project stored on different partitions in the sidebar.  Code crashed on opening the second one and was unstable until the first project was also closed.

### Steps to Reproduce

1. Have two folders with the same name on different partitions 
2. Try to open both as projects 
3. Crash

### Expected Behavior

No crash.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by aguillon** [comment]
Hi! Please note that I'm not one of the project maintainers.

Do you remember the name and paths of the two folders you added? I have been able to reproduce this by adding, e.g., `/usr` and `/home/arthur/usr`. I believe the issue appears when the two folders and their ancestors have the same names, pairwise, until we reach the root /.

Alternatively, would you have the time to try my fix?

**Comment by jeremypw** [comment]
@aguillon 

In my case I was opening the same project on two different partitions so the paths were something like:
1) `/home/jeremypw/Project1`
2) `/media/jeremypw/<UID>/home/jeremypw/Project1`

Thanks for having a try at fixing this!  Welcome to elementaryOS developing! I'll have a look at your PR.
