### ISSUE TITLE
Interest in maintaining the Flathub repo?

### ISSUE THREAD

**Issue by Alexander-Wilms** [elementary/code#152]
I created a Flatpak manifest for elementary Code: https://github.com/flathub/io.elementary.code

You can test it like this:
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub io.elementary.code
flatpak run io.elementary.code

Would you like to (co-)maintain that repository?

**Comment by baarkerlounger** [comment]
Is it a deliberate choice to not maintain Code on Flathub?

**Comment by danrabbit** [comment]
@baarkerlounger Yes that's correct. There will be an official elementary remote soon that we'll keep up to date with flatpak builds of our apps
