### ISSUE TITLE
Shortcut Cheatsheet Window

### ISSUE THREAD

**Issue by DroWnThePoor** [elementary/code#153]
For some time now I've wondered about shortcuts and hotkeys for, not only Scratch, but all of the native eOS apps. 
I know that ctrl+shift is the modifier for several things in Files and Terminal, but there's many simple commands that I can't figure out for several of these apps.

For instance: In Scratch, how do you "comment out" the selected line/text?

I feel we're lacking documentation for most of the apps eOS ships with, this is something I wouldn't mind working on, but I don't know the proper way to go about it?

**Comment by babluboy** [comment]
I would like to know the shortcut for Undo and Redo in Scratch. I tried Ctrl+Z and Ctrl+Y but they did not work. At the moment I'm using the right click context menu to achieve this, but a shortcut will be much more helpful.

Also Ctrl+S closes Scratch, this is a bit annoying as I'm used to do Ctrl+S to save edits in other editors ...great that scratch saves by default, maybe I have to change my habbit on this shortcut

**Comment by tintou** [comment]
@babluboy `Ctrl`+`Z` undo, `Ctrl`+`Shift`+`Z` redo

**Comment by babluboy** [comment]
@tintou Many thanks - will be good to have this documented on a GH Page. If you have a rough list somewhere then I can create a GH Page for the same similar to the one I have created for Bookworm here: https://babluboy.github.io/bookworm/#features

**Comment by DroWnThePoor** [comment]
@tintou I've been thinking about doing a user manual for Elementary, but haven't had the time to get started, and I haven't been able to decide on a format/platform to create it in. I thought about creating a repository with markdown files, as I'd prefer for this to be something I could start and the community can edit and add to.

**Comment by GammaGames** [comment]
I think it would be helpful if a little notification for the shortcut window popped up if you pressed a common shortcut that wasn't correct, like `Ctrl`+`Y` when you try to undo. I think this issue would be simplified if the shortcuts overlay had a way to get current app shortcuts ([shortcut-overlay/53](https://github.com/elementary/shortcut-overlay/issues/53)), too

**Comment by cassidyjames** [comment]
I think this is actually out of date since we've been adding shortcuts contextually throughout Code in the form of new tooltips. Aggregating those all into once place doesn't seem that helpful to me, as we want to make sure the contextual/visual way to accomplish something is clear, and _then_ also progressively disclose the shortcut way to do it.
