### ISSUE TITLE
Some glyphs are clipped at the line height

### ISSUE THREAD

**Issue by ThaisRobba** [elementary/code#182]
Likely to be related to #180.

Glyphs like `§` are clipped at the line height and result in weird rendering artifacts.

Clipped:
![screenshot from 2017-08-20 17-51-27](https://user-images.githubusercontent.com/597287/29498352-71c78ab6-85d0-11e7-967d-9426299f896b.png)

Artifacts
![screenshot from 2017-08-20 17-54-20](https://user-images.githubusercontent.com/597287/29498363-017f498c-85d1-11e7-9c86-f97a97f6b824.png)

Reproduction steps:
- Type the character `§`
- Notice the clipped part
- Press enter to create a newline
- Notice it is now displayed in full
- Press enter to create a newline
- Notice it is clipped again
- Press `backspace` 3 times
- Notice the remaining artifact

**Comment by danrabbit** [comment]
I can't reproduce this on elementary OS 6
