### ISSUE TITLE
Search only uses color to denote failure

### ISSUE THREAD

**Issue by snowparrot** [elementary/code#206]
I have problems seeing red and green. Dark red also looks more like black so e.g.
the search didn't find any item I can't see it on first glance. Other user can be confused, too because there is no other reaction.

**Comment by cassidyjames** [comment]
Ah we only use color to denote a failed search. We could probably also change the search icon in the entry to something to indicate no matches?

Go go gadget @elementary/ux

**Comment by snowparrot** [comment]
@cassidyjames Though a bit unrelated Accessbility should be discussed in HIG so coders are more aware of the problem.

**Comment by matzipan** [comment]
@snowparrot perhaps open an issue for the HIG on https://github.com/elementary/website/

**Comment by jorgemanzo** [comment]
I've taken a look in `SearchBar.vala` and it seems like we just add a `Gtk.STYLE_CLASS_ERROR` class to the `search_entry`. I couldnt find anything on valadoc for changing the icon on the search entry widget itself (though maybe I just missed it).

Would the way to accomplish this be to somehow modify the `Gtk.STYLE_CLASS_ERROR` class?
