### ISSUE TITLE
Auto-indent within brackets

### ISSUE THREAD

**Issue by Tvax** [elementary/code#212]
Would be awesome if the brackets would be auto-indented ! 
Also the cursor could be indented properly with your code when you hit return as well.

**Comment by danrabbit** [comment]
Do you have "automatic indentation" in preferences enabled?

Can you more thoroughly describe how the current behavior differs from the expected behavior?

**Comment by Djcoper** [comment]
I can confirm this is true for me in Scratch 2.4.1 on Loki 0.4.1 stable.

![ezgif-2-20f8eb2927](https://user-images.githubusercontent.com/30577249/31641913-de42e910-b2df-11e7-87d0-2588c492117a.gif)

**Comment by jeremypw** [comment]
I agree this would be a useful feature for a code editor.

**Comment by cassidyjames** [comment]
So it seems the expected/wanted behavior is:
1. Cursor is immediately after an opening bracket/parenthesis
2. User presses Enter
3. The cursor goes to the next line _and_ indents one more level
4. If there is a closing bracket/parenthesis immediately after, put it on the next line, un-intented back to the original line's indentation
