### ISSUE TITLE
Creating new file immediately opens it

### ISSUE THREAD

**Issue by donadigo** [elementary/code#213]
When creating a new file in the sidebar, Scratch shouldn't immediately open it in the editor with the "unnamed" name, but allow for renaming it, and after the renaming is done, the file should be loaded in the editor.

**Comment by matzipan** [comment]
I have a fix for this in the pipeline. Just needed to merge a few things
before it

**Comment by cassidyjames** [comment]
@matzipan any update?

**Comment by wout** [comment]
This behaviour feels very buggy. After creating a new, a prompt should be presented to give it a name. This issue makes me want to give up on Code since I use it so often and every time it's a hassle.
