### ISSUE TITLE
Cannot create backup copy

### ISSUE THREAD

**Issue by matzipan** [elementary/code#218]
When saving the contents of a newly created tab I get the following: 

```
[WARNING 22:18:38.268181] Document.vala:733: query_info failed, but filename appears to be correct, allowing as new file
[WARNING 22:18:38.268251] Document.vala:678: Cannot create backup copy for file "bla2.txt": Error when getting information for file '/home/matzipan/Downloads/bla2.txt': No such file or directory
```

**Comment by jeremypw** [comment]
I cannot reproduce this in master, although there is an issue with the no-restore-failed-doc PR.

**Comment by jeremypw** [comment]
Fixed no-restore-failed-doc

**Comment by jeremypw** [comment]
Closing as this has not been confirmed in the latest version.  Please reopen if this issue still exists in elementary 6.1
