### ISSUE TITLE
An external change on the file causes to stop saving and doesn't reload it's new content

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/code#228]
When a change on the file occurs externally, saving the file either via autosave or Ctrl+S doesn't apply the changes anymore.

Caused by #209

![peek 2017-09-30 20-41](https://user-images.githubusercontent.com/10786508/31050915-e422906e-a61f-11e7-960f-3b48620ca71c.gif)

**Comment by jeremypw** [comment]
Possibly https://github.com/elementary/scratch/commit/3c94a1e547d38e495d05ff9521330a41dcc19de5 ? This affected loaded of docs and indirectly may have affected saving.

**Comment by jeremypw** [comment]
I find that if Code tries to save to a file that has been externally modified, an error is thrown which is caught and gives the warning ```"Cannot save [ FILENAME ]: The file is externally modified"``` in the terminal.  This part of the code was not changed by the above-mentioned commit, so must have changed elsewhere.  This explains why Scratch no longer saves changes.  It is clearly unsatisfactory that this happens silently.

It is noted that Gedit, for example, detects external file changes (presumably with a FileMonitor) and gives a warning with the option to load the external changes or overwrite them.  

Need design input for the correct/desired behaviour of Code.

**Comment by matzipan** [comment]
I think imitating Gedit behavior here is good practice.

**Comment by danrabbit** [comment]
Yeah this is annoying, AF. I assume that Code always has the most up to date version of the file loaded and would refresh automatically (this was the previous behavior)

**Comment by jeremypw** [comment]
There have been significant relevant changes to master and I do not think this applies any more. Best to open new issues in relation to the current master.
