### ISSUE TITLE
Cannot continue instead of reloading external changes.

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#230]
If "autosave" is turned off, then if a file being edited is changed externally an info bar is shown when Code is re-focused. This gives the options to ReLoad or Continue.  The former option works, but if the second is chosed, the info bar reappears as soon as the sourceview is clicked on (due to the generation of another focus-in-event).  The next focus-in-event needs to be ignored when the infobar is hidden.

**Comment by mcclurgm** [comment]
This still happens in version 3.4.0. But to clean the bug list a bit (after 2 years!), this is the same as #17.

**Comment by jeremypw** [comment]
Fixed in 0c49cb792344b15160a67294da74574b904913b8
