### ISSUE TITLE
Missing spell check in file extensions other than *.txt

### ISSUE THREAD

**Issue by andreppi** [elementary/code#234]
Apparently the spell checker plugin does not work when editing a code file.
https://github.com/elementary/scratch/blob/2a6fdb9556efae94d521ab966da7f19dc8d1ada8/plugins/spell/spell.vala#L106

It's something that I miss, particularly when I'm editing Latex files. What are your thoughts on this?

**Comment by cassidyjames** [comment]
I think it would be reasonable to enable this in md files at the very least. But since Code is not intended to be a prose editor and is focused on code editing, I wonder if we could be more smart about also spellchecking in strings of all languages?

**Comment by cassidyjames** [comment]
In #827 we're handling the language `id` of `markdown`, and we could add `latex` there as well. _Or_ we could try adding any language whose `section` is equal to `markup` (which includes Markdown and LaTeX), but that would group in HTML and whatnot, which is ugly. I think before we do that, we'll need to make the spell check extension only check in strings/not in tags/code.
