### ISSUE TITLE
Add a filter entry for syntax highlighting

### ISSUE THREAD

**Issue by danrabbit** [elementary/code#246]
because "Fuck dropdowns"

**Comment by aleksandar-stefanovic** [comment]
Something like this?
![screenshot from 2017-12-11 14 52 04](https://user-images.githubusercontent.com/6058082/33834382-0f509b32-de83-11e7-93f6-07915a8baccd.png)

If so, should the `Entry` float upon scrolling, or be scrolled with the rest of the content?

**Comment by davidmhewitt** [comment]
Fixed in https://github.com/elementary/code/pull/287
