### ISSUE TITLE
When auto-saving, recent changes are gone sometimes

### ISSUE THREAD

**Issue by lainsce** [elementary/code#272]
When auto-save kicks in, sometimes some if not all recent changes are deleted from the file, resulting in loss of data.

**Comment by cassidyjames** [comment]
@lainsce what plugins are you using?

**Comment by lainsce** [comment]
Default plugins that are activated on first launch.. :confused:

**Comment by lainsce** [comment]
Can confirm, later versions do not have this problem anymore. :smiley:
