### ISSUE TITLE
Make Install error: missing ".desktop" file 

### ISSUE THREAD

**Issue by yufelipeto** [elementary/code#279]
Cmake shows an error while installing:
```
CMake Error at data/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/yurefelipeto/Code/data/org.pantheon.scratch.desktop".
```

**Comment by cassidyjames** [comment]
Can't reproduce here. @yufelipeto what OS are you on? Does this still occur?

**Comment by davidmhewitt** [comment]
Closing as code no longer uses CMake.

Please let us know if there are still any issues with the new meson build system.
