### ISSUE TITLE
html tags appear in the titles of some dialogs

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/code#281]
As shown here, some dialogs seem to show tags like `<b>` within their titles.

![screenshot from 2017-11-22 23 20 53](https://user-images.githubusercontent.com/831389/33152721-668b7ccc-cfde-11e7-85cc-855d107d619c.png)

**Comment by aleksandar-stefanovic** [comment]
Is this fixed? Here's how the dialogs look for me:
![image](https://user-images.githubusercontent.com/6058082/33516225-9419a1a8-d76f-11e7-8f96-f5dd8d5d6580.png)

**Comment by lewisgoddard** [comment]
Scratch still shows it for me on Loki with the daily ppa. Are you using a test-build?

![image](https://user-images.githubusercontent.com/831389/33521155-1cfd1f2a-d7c2-11e7-9440-49286edc3ad3.png)

**Comment by jeremypw** [comment]
Whether you experience this depends on which version of Granite you have.

**Comment by danrabbit** [comment]
It looks like this has been changed and there are no longer bold tags in these strings, so I guess it's been fixed
