### ISSUE TITLE
"Strip trailing whitespace" plugin occasionally eats files

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#305]
If I enable the "Strip trailing whitespace" plugin, sometimes when Code saves my files, the contents are actually completely deleted from the disk, even though the code is still visible in the editor. Changing a whitespace character and re-saving appears to restore the contents of the file. 

This is observable when building an app; if you make a change in Code and then go to compile, you get errors about classes from the open file not existing. If you commit the code, you see that the entire contents of the file has been deleted, even though it's still visible in the open Code window.

Here's an example of one such case; I changed a line, switched to Terminal, and committed it. This is the resulting commit:
https://github.com/cassidyjames/dippi/commit/ef5778d325e19ec8097ad7de937f51c00ef2f2a2

I changed a whitespace character and re-committed it. This is the resulting commit: 
https://github.com/cassidyjames/dippi/commit/5c45d39fe2f0d7acd0bb9c4116f5d3fa6c025888

**Comment by cassidyjames** [comment]
The scary thing is if I would have closed Code after changing a line, I'm not sure if I would have completely lost the file or not. Luckily in this case I could see from the Terminal that something was weird while Code was still open.

**Comment by danrabbit** [comment]
@cassidyjames can you see if you can still reproduce the issue after David's branch just got merged?

**Comment by cassidyjames** [comment]
I'm pretty sure it was fixed, but I'll keep my eye out for it.

**Comment by davidmhewitt** [comment]
Going to close this as I've not seen this happen for a while and I'm guessing nobody else has either?

Can always be reopened!
