### ISSUE TITLE
Wrap brackets when highlighted

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#311]
Something I always love when in Atom is the ability to highlight some text, then hit an opening bracket or quote key to wrap the text in that set of brackets/quotes. I'm not sure if this would belong in the bracket completion plugin, as a separate plugin, or as a core feature.

Example (with `(bar)`):

![gifout](https://user-images.githubusercontent.com/611168/34957665-c995a464-f9eb-11e7-952d-cb138cf14930.gif)

**Comment by cassidyjames** [comment]
Never mind, it appears to be doing this. I wonder if it just doesn't work reliably, because I swore it didn't. Closing. :P

**Comment by jeremypw** [comment]
Still working for me.  (Other plugins in use are "Bracket Completion",  "Detect Indent" and "Highlight selected Word".  Auto indentation is on)

**Comment by ottohak** [comment]
This bracket wrap feature is provided by the "Bracket Completion" Plugin.

The function [complete_brackets](https://github.com/elementary/code/blob/master/plugins/brackets-completion/brackets-completion.vala#L126) adds the character after the selected section in line [144](https://github.com/elementary/code/blob/master/plugins/brackets-completion/brackets-completion.vala#L144).

**Comment by cassidyjames** [comment]
Yeah this is working again for me, I think I had a weird local install.
