### ISSUE TITLE
Toggle line comment

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#313]
A feature that I miss from Atom is the shortcut to toggle a line-level comment. It's super handy for commenting/uncommenting a line of code quickly while testing things.

In Atom, it's `Ctrl`+`/`. In Code that appears to select all text, so I'm not sure if we want to override that or come up with a different shortcut.

**Comment by davidmhewitt** [comment]
Currently working on a plugin to do this (and block comments for the selection) here:
https://github.com/elementary/code/tree/toggle-code-comments-support

Currently supports commenting out lines or blocks of code with the Ctrl+M shortcut. Need to get it to toggle comments off again.
