### ISSUE TITLE
Unguesable arrows in find

### ISSUE THREAD

**Issue by Philosoft** [elementary/code#331]
### How to reproduce

1. Open any file
1. Search anything
1. try to guess does there are any matches above or below of visible content

Related screenshot: 
![scraatch-blur](https://user-images.githubusercontent.com/296326/35802173-160f214a-0a80-11e8-8ab9-c4fe11318627.png)

On screenshot above: there are several matches below and none above visible content, but I can't deduce it from color of arrows or any visible message/status line. And status line is not an ultimate answer to this issue. It's frustrating.

**Comment by cassidyjames** [comment]
This is probably a general contrast issue with the [stylesheet](https://github.com/elementary/stylesheet).
