### ISSUE TITLE
hide sidebar 

### ISSUE THREAD

**Issue by ho3ein-mola** [elementary/code#341]
First : is there any way to toggle  file and project manager . for instance press <alt>+1 to toggle sidebar 
Second :  if you add fuzzy search it will be really clean code editor .

**Comment by cassidyjames** [comment]
> is there any way to toggle file and project manager . for instance press +1 to toggle sidebar

There's not at the moment, but I'd be interested in adding that.

>if you add fuzzy search it will be really clean code editor .

This would be considered a separate issue, and I believe what you're asking for is open at https://github.com/elementary/code/issues/134

**Comment by cassidyjames** [comment]
The main question around the sidebar is how to toggle it. A shortcut on its own is not sufficient; if a user accidentally hides it, they need to be able to get it back graphically. We could add a button in the headerbar, but that feels a bit heavy. In other apps we've used a button in a statusbar/bottom toolbar, but we don't have one of those in Code and I'm not sure we want to introduce one just for this.

Atom uses a floating tab thing for their collapsible panels. They appear when hovering over or near the panel/sidebar, but that feels like it might get in the way. They also have it in the menu and via shortcuts (Ctrl + \), and in the command palette.

| ![screenshot from 2018-04-14 12 32 39](https://user-images.githubusercontent.com/611168/38771465-0d3dd6ce-3fe1-11e8-8434-d0fa9538d745.png) | ![screenshot from 2018-04-14 12 32 48](https://user-images.githubusercontent.com/611168/38771491-59a51d6a-3fe1-11e8-9e5d-ab02f0913fd5.png) | ![screenshot from 2018-04-14 12 32 57](https://user-images.githubusercontent.com/611168/38771492-5c6f2284-3fe1-11e8-8d96-3182d7231784.png) | ![screenshot from 2018-04-14 12 33 03](https://user-images.githubusercontent.com/611168/38771493-5d7a5270-3fe1-11e8-9d59-08ee7c76190e.png) |
|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| Open, mouse in editor | Open, mouse in or near sidebar | Closed, mouse in editor | Closed, mouse near sidebar |

VS Code does a simpler sideways tab bar thing, plus a shortcut (Ctrl + B). Plus the command palette.

| ![screenshot from 2018-04-14 12 31 42](https://user-images.githubusercontent.com/611168/38771512-a72df35e-3fe1-11e8-9c33-fd9bda105290.png) | ![screenshot from 2018-04-14 12 31 53](https://user-images.githubusercontent.com/611168/38771516-b5cc513a-3fe1-11e8-9a71-4af0845fd68e.png) |
|--------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------|
| File tab selected | File tab clicked again |

Sublime just uses their command palette or menubar plus shortcuts (tap Ctrl + K then Ctrl B).

**Comment by cassidyjames** [comment]
GNOME Builder uses the somewhat standard GNOME shortcut of <kbd>F9</kbd> which shows in the keyboard shortcuts dialog, plus a togglebutton in the headerbar

![screenshot from 2018-04-14 13 26 09](https://user-images.githubusercontent.com/611168/38771836-7034a856-3fe7-11e8-85ab-4509899534a4.png)

**Comment by SixFingeredAmish** [comment]
I think adopting Atom's shortcuts would be a good idea. They are close to universal I think.

**Comment by nuclearfall** [comment]
Just as an alternative. I really like the way Bear handles this. It's probably the most aesthetically pleasing app I've come across. It uses CMD/Super 1,2,and 3 for it's three main views/and a small icon with an iconographic popover menu in the lower right hand corner of the main viewport. 

<img width="1317" alt="screen shot 2018-08-29 at 3 26 44 am" src="https://user-images.githubusercontent.com/41907342/44775652-bef5cc80-ab3b-11e8-8182-6f978752aa7f.png">

**Comment by cassidyjames** [comment]
I think now that we have the unified menu with the style switcher and a place to get to preferences, I would be fine tucking a sidebar item in there with a keyboard shortcut listed to aid in discoverability. That feels more natural to me than adding an icon to the editor view.
