### ISSUE TITLE
Add "Open with" to context menu in the sidebar

### ISSUE THREAD

**Issue by danrabbit** [elementary/code#356]
This should mimic the behavior we have for the context menu in Files and Photos with the submenu showing compatible apps.

There are two questions:

* ~~Files has "Open in" and Photos has "Open With…" as the label. Not sure which is correct here~~. It sounds like we wanna use "Open In" since it's more flexible with options like "New Window". According to the HIG, submenus should not use ellipsis.

* Photos shows icons for apps, Files does not. I personally like the icons for apps but I'd like confirmation from someone else on @elementary/ux

**Comment by cassidyjames** [comment]
I like icons for apps, since that's a huge part of an app’s brand.
