### ISSUE TITLE
confusing behaviour when using the "save as" on new document

### ISSUE THREAD

**Issue by eppixx** [elementary/code#381]
Steps to reproduce:
1. create new document
2. use the "save as" option -> the tab changes to filename
3. further edit the file
4. closing the tab

By closing the tab the edits in point 3 are discarded. Code doesn't warn you.
I expected the editor to save my file like it does when opening files on the fly without manually saving it.

**Comment by cassidyjames** [comment]
I apparently lost data to this today. 😬

**Comment by ethanay** [comment]
Is this message related? 
[WARNING 10:12:45.459523] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:12:51.834223] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.

**Comment by ethanay** [comment]
Ok, this might be related. I can reliably reproduce this behavior.
1. I type a bunch of stuff
2. *Immediately* after typing I press ctrl + shift to begin keyboard highlighting some stuff
3. The cursor jumps to the beginning and the above-mentioned error message appears
4. Upon further investigation, not only has the document not saved, but some other weird things have happened: First undo operation produces a COMPLETELY BLANK DOCUMENT. Subsequent undo operations restore the document. 

So there is potential for complete and catastrophic data loss, here, which is exactly what happened to me! :(

I cannot reproduce this behavior when "save document when modified" is disabled. So it appears that that feature is to blame for data loss. I am not quite sure what happened with my day's work, but I believe that somehow the modifier key press interferes with the save operation and causes other undesirable behaviors very quickly.

**Comment by ethanay** [comment]
Here is the full terminal log:
$ io.elementary.code
[WARNING 10:12:45.459523] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:12:51.834223] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:24:08.965710] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:24:13.969764] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:25:58.361517] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:26:00.443736] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:26:47.686761] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:26:54.768218] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:27:28.907524] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:27:33.224061] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[FATAL 10:28:51.316673] scratch_widgets_document_view_get_current_document: assertion 'self != NULL' failed
[WARNING 10:29:05.019679] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
[WARNING 10:29:10.351240] Document.vala:456: Cannot save "Keyline_SOP.txt": The file is externally modified.
Gtk-Message: 10:39:25.098: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 10:40:55.800: GtkDialog mapped without a transient parent. This is discouraged.
[close program]

Each of those "warning" messages above was an example of when/where/how loss of the the ENTIRE document data could occur.

**Comment by ethanay** [comment]
It occurs with/without multiple tabs open. I believe this and #551 are the same bug, and the issue is with the "save files when changed" feature or something related to its implementation.
