### ISSUE TITLE
Goto Anything

### ISSUE THREAD

**Issue by jwinnie-the-great** [elementary/code#389]
The “Goto Anything” feature in Sublime combines file searching, symbol searching and jumping to a line. I think it should be adopted in elementary Code.

From the Sublime website:
> Use Goto Anything to open files with only a few keystrokes, and instantly jump to symbols, lines or words. Triggered with ⌘+P, it is possible to: Type part of a file name to open it. Type @ to jump to symbols, # to search within the file, and : to go to a line number. These shortcuts can be combined, so tp@rf may take you to a function read_file within a file text_parser.py. Similarly, tp:100 would take you to line 100 of the same file.

**Comment by jeremypw** [comment]
I think this is essentially fixed by the Global Search feature currently in Code.
