### ISSUE TITLE
how to write plugins

### ISSUE THREAD

**Issue by rythmkraze** [elementary/code#393]
Is there a tutorial on how to write plugins for elementary Code?
Also, once written, is there a way to add the plugin to Code instead of compiling the plugin along with the main application?

Code is the most elegant text/code editor I have ever used. Making it easy for third party developers to build and publish (may be via app center) plugins will allow the elementary ecosystem to grow. 
Thanks in advance.

PS: elementary OS fan here :)

**Comment by tintou** [comment]
Code allow to have plugins but work is done in the API and no guarantee is made on its stability until further notice. On Loki, you have the libscratchcore-dev package that provides all the required API hooks to create out-of-tree plugins. Just look at the current existing plugins to understand how it's working.
We don't plan to create any tutorial about it right now as the API is unstable. But feel free to experiment with it.

**Comment by rythmkraze** [comment]
Thanks for pointing me in the right direction.

**Comment by MichaelJGW** [comment]
It has been a year is there any status update on the API's stability?
