### ISSUE TITLE
Folders are selectable in the sidebar

### ISSUE THREAD

**Issue by jwinnie** [elementary/code#408]
It doesn't make sense that folders are selectable:
![folderclick](https://user-images.githubusercontent.com/20506149/39391105-45b4781a-4a53-11e8-8dba-f1ed9b9b6583.gif)
Folders should expand/collapse when clicked.

**Comment by berliner** [comment]
Depends, for things like https://github.com/elementary/code/issues/418 it might actually make sense to be able to select folders by clicking on them. In TextMate 2 (mac), that's a way of selecting the search scope and it's working really well.

**Comment by marbetschar** [comment]
I agree. Stumbling a lot across folders which do not automatically open in Code which is quite annoying. Event though it *might* make sense to select folders for search, I'd argue that use case happens way less often than expanding/collapsing folders.

That said, the default behavior in my opinion should be expanding/collapsing. If selecting makes sense, then this could be done using Ctrl + click. That's also the way it works in the Files app.

**Comment by jeremypw** [comment]
This also happens in granite-demo so seems to be a "feature" of the underlying widget used (Granite.Widgets.SourceList).  Maybe able to override, but if not then will need to move issue to Granite project.
