### ISSUE TITLE
Build Code Error : GtkSourceView > 3.24 on Loki

### ISSUE THREAD

**Issue by aswinmohanme** [elementary/code#416]
When building from the git repo on Loki, meson throws this error

`meson.build:20:0: ERROR: Invalid version of dependency, need 'gtksourceview-3.0' ['>=3.24'] found '3.18.2'.`

**Comment by tintou** [comment]
Yes, Code is now targeting the next version of elementary. To build Code on Loki, you can use `apt-get source scratch-text-editor` and build this version.

**Comment by aswinmohanme** [comment]
But that would allow only scratch-text-edtitor to build this version right ?

**Comment by tintou** [comment]
yes, newer version requires newer components that unfortunately cannot be backported to Loki
New version of elementary should come soon®
