### ISSUE TITLE
[REQUEST] Add Typescript Support

### ISSUE THREAD

**Issue by btd1337** [elementary/code#417]
Is It possible to add Typescript language support?

**Comment by jwinnie** [comment]
If #220 is implemented then TypeScript support should be easy

**Comment by eyelash** [comment]
[This](https://github.com/jefferyto/gtksourceview-js-lang) might be useful.

**Comment by eyelash** [comment]
Some basic TypeScript support (syntax highlighting) was [just merged](https://gitlab.gnome.org/GNOME/gtksourceview/merge_requests/63) into GtkSourceView.

**Comment by chances** [comment]
Is this now moot given #837?
