### ISSUE TITLE
[UX] Always return focus on main file

### ISSUE THREAD

**Issue by Alecaddd** [elementary/code#419]
When I click on a file to open it, would be great if the focus would go directly on the file in order to allow the user to immediately start typing or closing the file with `Ctrl+w`.
Sometime, I quickly skim through multiple files and I'd really love to be able to open and close multiple files.
Same goes when I have lots of files open and I'd like to close them quickly one by one by hitting `Ctrl+w` continuously without clicking every time on every single file.

**Comment by cassidyjames** [comment]
Not sure if this is by design, or a bug, but yeah. Rapid-hitting Ctrl+W should close a file each time I hit it, and not require me to click inside of each file each time.
