### ISSUE TITLE
Patch the default styles

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#464]
As mentioned in #318 and #433, the default styles are pretty bad with their whitespace and selection colors. We could ship lightly patched versions of the defaults to get around this.

**Comment by davidmhewitt** [comment]
Would the thought be to ship the styles as part of Code (i.e. in it's data folder) and have it load them from there instead of the systemwide Gtksourceview ones?

I could probably fairly quickly throw together a branch that would let you play around with the styles a bit.

**Comment by tintou** [comment]
Whoever does this *MUST* send a patch upstream

**Comment by cassidyjames** [comment]
@tintou naturally :stuck_out_tongue:

**Comment by cassidyjames** [comment]
@davidmhewitt we do ship some stuff in the OS repo, I believe. So that might be the better place to handle this, actually.

**Comment by davidmhewitt** [comment]
Above branches have now both been merged so we should hopefully be seeing some better contrast with the space drawing in those branches.
