### ISSUE TITLE
[Request] Add Ren'Py Language Support

### ISSUE THREAD

**Issue by alicerunsonfedora** [elementary/code#467]
I think it'd be extremely helpful if you added support for syntax highlighting in Ren'Py's language. I know of an Atom extension that does this: https://github.com/renpy/language-renpy

It's also supported in Sublime Text with extensions. I am sort-of getting away with it as Python, but it's not ideal.

**Comment by tintou** [comment]
Thanks for the issue.
We are using GtkSourceView here, the same component as GEdit, you can download the .lang file from https://www.renpy.org/wiki/renpy/Editors#gedit-gtksourceview and put it inside of ~/.local/share/gtksourceview-3.0/language-spec/
If you feel that this should be available out-of-the-box feel free to open an issue on GtkSourceView itself https://gitlab.gnome.org/GNOME/gtksourceview
