### ISSUE TITLE
[Request] Add Solidity Language Support

### ISSUE THREAD

**Issue by aadilayub** [elementary/code#468]
I use elementary OS to learn how to make ethereum dApps. I would prefer to use the native code editor for all my programming needs, but most of the files I open for work are really hard to read due to the lack of syntax highlighting.

It would be great if elementary-code had a plugin for Solidity linting!

**Comment by cassidyjames** [comment]
@aadilayub from a cursory glance, nobody has made a GTKSourceView language spec for Solidity, which is what Code would use to syntax highlight it. There are some docs here: https://developer.gnome.org/gtksourceview/stable/lang-tutorial.html

I know this is something other users of Solidity have been asking for as far back as 2016. If/when someone puts it together, we could ship it in elementary OS.

**Comment by aadilayub** [comment]
@cassidyjames I'm looking into putting together the language spec. Is this something that has to be patched upstream to GNOME, or does there just need to be an XML file?

**Comment by davidmhewitt** [comment]
elementary ships some extra language files to upstream, so it could be shipped as part of elementary's patched version of gtksourceview.

Though I'm sure upstream would appreciate a PR too.

**Comment by davidmhewitt** [comment]
I'm going to close this due to inactivity. If there is a complete language spec that you'd like to be included, you can submit an issue/PR in this repository: https://github.com/elementary/os-patches/issues

There is a branch called `gtksourceview3-bionic-patched` which includes extra language specs shipped by elementary.
