### ISSUE TITLE
Code doesn't respect "Privacy → History" setting

### ISSUE THREAD

**Issue by uncertainquark** [elementary/code#473]
Unlike Scratch, Code always remembers the last open files even if the "Privacy > History" setting is off. Moreover, the option to turn off remembering last open files, which Scratch had, is missing.
![screenshot from 2018-07-08 21-00-28](https://user-images.githubusercontent.com/22585732/42421385-6d39c26e-82f2-11e8-902b-956fa5abb09e.png)

**Comment by cassidyjames** [comment]
I've clarified the scope of this issue a bit; apps should respect the system-wide setting instead of implementing their own.
