### ISSUE TITLE
Code doesn't start

### ISSUE THREAD

**Issue by zimnyd** [elementary/code#495]
The code just not open from icon. When try to open from command line I have such error:

`[FATAL 14:17:03.781170] [GLib] g_str_has_prefix: assertion 'str != NULL' failed`
`[FATAL 14:17:03.782543] [GLib] g_str_has_prefix: assertion 'str != NULL' failed`
`Memory protection violation`

My system:
`Distributor ID:	elementary`
`Description:	elementary OS 5.0 Juno`
`Release:	5.0`
`Codename:	juno`

**Comment by j-a-n** [comment]
Same problem here.
How did you resolve the issue?

**Comment by iluyx** [comment]
In this url you could find the solution: 

https://github.com/elementary/code/issues/544#issuecomment-433924109

Duplicate of #544
