### ISSUE TITLE
Code should execute when I type code in terminal

### ISSUE THREAD

**Issue by skewty** [elementary/code#510]
If I want to edit a file with 'Code" editor, I should be able to type
$ `code ~/Documents/some_file.txt`
But this instead brings up a suggestion to install VisualStudio Code.
Totally not what I was expecting.

**Comment by leonardo-lemos** [comment]
The Code's binary is named in the RDNN format. You should be able to find it as io.elementary.code. The RDNN format prevents ambiguous reference to a binary, like the elementary's Code and the Visual Studio Code.
