### ISSUE TITLE
Code should not create backup~ files~ in Git projects

### ISSUE THREAD

**Issue by jlnr** [elementary/code#516]
The automatic backup system makes my git status harder to follow while providing little value, since I already use git for these files anyway.

**Comment by cassidyjames** [comment]
These files are removed automatically when the tab is closed, but I agree that they can be annoying in Git projects. But I don't know if just simply not saving them is the right answer.

**Comment by tintou** [comment]
Add `*~` in your .gitignore, the ~ suffix is a common way to represent backups

**Comment by jlnr** [comment]
I've only ever encountered this convention in Code and gedit, but Google says vim and emacs do the same thing; TIL.

I guess my suggestion to disable this feature in git directories was a bit too clever. I've opened up #517 instead, because I think a global on/off toggle would be more appropriate.
