### ISSUE TITLE
Add custom gtksourceview 3.0 theme

### ISSUE THREAD

**Issue by vlad1777d** [elementary/code#518]
Hello.

In Linux Mint's Xed editor I can add gtksourceview theme to `~/.local/share/gtksourceview-3.0/styles` direcotory and Xed will see it.

Same I can do for Elementary OS and Scratch.

But what to do in Code, which was installed using Flatpak ?
It has only built-in themes.

I suggest to add it button, after pressing on which user can select his theme file (anywhere it's placed) and add it to list.
It's currently implemented in Xed:
![screenshot from 2018-10-06 19-11-56](https://user-images.githubusercontent.com/12682937/46573293-e55d2200-c99b-11e8-93df-c3d04d0131d4.png)

After pressing on that button, I can add theme, which can be placed anywhere in file system.

I'd be grateful if this could be fixed.

Thanks.

**Comment by cassidyjames** [comment]
First, elementary does not distribute Code as a Flatpak. Any Flatbak build would be third-party and entirely unsupported.

Second, Code is designed to be simple and straightforward. Infinite customizability isn't the goal, so adding an arbitrary color scheme loader is not likely something we'll add. However, there's an open issue and discussion (with a linked PR) to make the style picker more adaptable for distributors or advanced users: https://github.com/elementary/code/issues/395

**Comment by GarkGarcia** [comment]
> Second, Code is designed to be simple and straightforward. Infinite customizability isn't the goal, so adding an arbitrary color scheme loader is not likely something we'll add.

I really think you guys should reconsider this. I understand the issue of excessive customizability and the ["Please don't theme our apps"  thing](https://stopthemingmy.app/), and I absolutely agree, but I don't think this applies to a code editor. 

A code editor is usually where a programmers spends most of his/her time while developing, it's a very intimate place in a way. Not being able to customize the color-scheme in a code-editor is a deal breaker for most programmers I know.

Keep in mind I'm advocating for an option to import arbitrary _GtkSourceView themes_ (which would only affect the main text-box, altering the colors of the syntax-highlighting), not arbitrary _GTK themes_ (which would affect the entire app). This should be really simple to do, GtkSourceView already supports custom color-schemes. It's just a matter of creating a GUI option for the user to import/select his/her custom theme.

**Comment by cassidyjames** [comment]
Again, please see the earlier linked issue. That issue is still open, and this would effectively be a duplicate of it.

**Comment by GarkGarcia** [comment]
> Again, please see the earlier linked issue. That issue is still open, and this would effectively be a duplicate of it.

I see. At first I didn't realize why you considered this a duplicate of #395 , but after reading the discussion in #434 I think I get it. The PR makes the color schemes displayed in the settings menu customizable (via the gsettings). Still, I think there is a relevant discussion in here: we should think about making this customization option accessible to the end user via the GUI.
