### ISSUE TITLE
New unsaved document not restored

### ISSUE THREAD

**Issue by markodp** [elementary/code#524]
To reproduce:
1. Create new document and add some text
2. Close the app
3. Open it back up - no document, just welcome screen

You are not asked to save the file before exit and it's not shown when opening back Code. That's not expected behavior and can lead to data loss.

**Comment by marcelogdeandrade** [comment]
What is the best approach to this issue? A simple dialog to confirm if you want to save the file or exit without saving?

I can fix this issue

**Comment by marcelogdeandrade** [comment]
So, the app saves the temporary file when closing the app in the folder `~/.local/share/io.elementary.code/unsaved`. There are some methods to check if there are temporary files, but there aren't any methods loading these files or deleting them.
