### ISSUE TITLE
Not defined "markup"?

### ISSUE THREAD

**Issue by Dirli** [elementary/code#525]
warning: Gtk.Widget.override_font has been deprecated since 3.16
../pantheon-code-9999/src/FolderManager/ProjectFolderItem.vala:120.21-120.26: error: The name `markup' does not exist in the context of `Scratch.FolderManager.ProjectFolderItem.do_git_update'
                    markup = "%s <span size='small' weight='normal'>%s</span>".printf (file.name, branch.get_name ());
                    ^^^^^^
../pantheon-code-9999/src/FolderManager/ProjectFolderItem.vala:197.17-197.27: error: The name `markup' does not exist in the context of `Scratch.FolderManager.Item?'
                item.markup = null;
                ^^^^^^^^^^^
Compilation failed: 2 error(s), 1 warning(s)

**Comment by davidmhewitt** [comment]
This looks like you're trying to compile Code with an older version of Granite. It requires version 5.1.0 or newer.

Going to close this issue as Code compiles fine with the correct dependencies.
