### ISSUE TITLE
Syntax highlighting language icon missing?

### ISSUE THREAD

**Issue by sixtyfive** [elementary/code#536]
Installed all dependencies, then compiled and installed `master` (not under Elementary, but under Solus). Code runs just fine, except for one small thing: the icon showing what the selected programming language for syntax highlighting is missing. I don't much care for there to be any icon at all, but if none can be found, I'd definitely prefer to have no icon at all showing instead of a "missing icon" icon.

![image](https://user-images.githubusercontent.com/192860/47111858-fbe56200-d254-11e8-8793-ae042410f29e.png)

**Comment by davidmhewitt** [comment]
The icon used here is `application-x-class-file-symbolic` and is provided by the icon theme. The fact it is missing for you means that the icon theme you are using does not provide that icon.

A quick search seems to suggest that there aren't many icon themes that provide this icon, but it is using a standard and correct icon naming convention for mimetype icons. I would suggest raising an issue against the icon theme you are using.
