### ISSUE TITLE
(Syntax Highlighting) Add Support for Elixir

### ISSUE THREAD

**Issue by DeadSuperHero** [elementary/code#539]
The new release of Code for ElementaryOS looks great, and I'm excited to start using it as my daily driver! One thing that I noticed, however, is that my language of choice ([Elixir](https://elixir-lang.org/)) is not currently supported within the editor.

I'm curious, what does it take to add highlighting support for new languages in Code? As someone that's currently learning the ins-and-outs of the language, this would be incredibly useful for me.

Is there a defined process for this?

**Comment by worldofpeace** [comment]
Someone would have to contribute it to the underlying library `gtksourceview` in [here](https://gitlab.gnome.org/GNOME/gtksourceview/tree/master/data/language-specs).

They have erlang already which is very similar for obvious reasons, so it shouldn't be too difficult as someone could iterate off of that slightly.

**Comment by davidmhewitt** [comment]
It looks as though someone has already created the necessary gtksourceview files for elixir: https://github.com/SteffenBauer/elixir-gtksourceview

The readme file details where you have to install the files for them to be picked up. So you could do this manually on your system. Or, elementary also ships a patched version of gtksourceview that already includes more languages than the version of gtksourceview that would ordinarily be shipped with Ubuntu.

So, if you test the elixir language support found above and believe it to be complete and useful, you can submit a proposal to have it included by default in elementary here: https://github.com/elementary/os-patches/issues
