### ISSUE TITLE
Crash on restoring file from inaccessible Samba share on startup

### ISSUE THREAD

**Issue by darkwyrm** [elementary/code#544]
I opened the app literally just once and didn't do anything with it -- just wanted to see what it looked like. I closed it, and opened it again a day later and it crashes immediately. Running from Terminal displays the following output:

[FATAL 08:22:35.869967] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
[FATAL 08:22:35.871144] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
Segmentation fault

Even tried uninstalling/reinstalling. No joy.

**Comment by darkwyrm** [comment]
I just found a step that I had forgotten -- I thought I had just opened and closed it. Nope. :)

When starting, an assumption is made somewhere along the line that the file is accessible. I had opened a text file on a Samba share which was not mounted the next time I attempted to open Code.

Steps to reproduce:
1) Mount a Samba share via GVFS
2) Open a text file on the share in Code
3) Close Code
4) Unmount Samba share
5) Re-open Code
6) *CRASH*

**Comment by razvanelli** [comment]
i get the same error when i try open Code 
![screenshot from 2018-10-23 09-40-03](https://user-images.githubusercontent.com/44391399/47340713-c7840280-d6a7-11e8-8b1e-6f2e59f2917d.png)

**Comment by davidmhewitt** [comment]
A note that might help some people get unstuck with issues like this; if Code isn't starting and you suspect it's due to files you've opened in the past, you can run the following command in the terminal to clean any settings and saved state:
`dconf reset -f /io/elementary/code/`
