### ISSUE TITLE
Blank screen when pressing New File after opening with sudo

### ISSUE THREAD

**Issue by linkert** [elementary/code#546]
![screenshot from 2018-10-23 14-54-10](https://user-images.githubusercontent.com/44402757/47361961-8dc8f100-d6d3-11e8-8da3-d221d8752511.png)

Screenshot shows after clicking New File.

**Comment by tintou** [comment]
Hi! Thanks for the report!
Can you try to open the terminal and open Code using `G_MESSAGES_DEBUG=all io.elementary.code` then paste the output of the terminal. This might give more information about what's wrong.

**Comment by linkert** [comment]
```
G_MESSAGES_DEBUG=all io.elementary.code
(io.elementary.code:6731): Gtk-DEBUG: 15:03:34.530: Connecting to session manager
[FATAL 15:03:37.843052] DocumentView.vala:149: Error opening file “/home/linkert/.local/share/io.elementary.code/unsaved/Text file from 2018-10-23 15:03:37”: Permission denied
```

**Comment by arshubham** [comment]
This issue happened to me a lot in loki. simply running `chown $USER:$USER ~/.local/share/io.elementary.code/unsaved` solves the issue.

**Comment by linkert** [comment]
Thank you very much! Seems like such an odd thing to just happen?

**Comment by davidmhewitt** [comment]
Did you run code as root or under sudo at any point?

**Comment by linkert** [comment]
I did run it under sudo at one point to edit samba config file. I then later heard from Cassidy on Reddit that it's not recommended and that it could fudge up the file I'm opening but yeah, I did.

**Comment by arshubham** [comment]
Duplicate issue https://github.com/elementary/code/issues/202

**Comment by davidmhewitt** [comment]
Closing as duplicate
