### ISSUE TITLE
Default logo for Find function is difficult to see in Dark mode

### ISSUE THREAD

**Issue by BNolet** [elementary/code#547]
![image](https://user-images.githubusercontent.com/10198484/47399535-e82f7500-d706-11e8-802c-4ba3e47b0696.png)
when unfocused

![image](https://user-images.githubusercontent.com/10198484/47399539-ef568300-d706-11e8-994d-d4900c6062f0.png)
when focused

**Comment by danrabbit** [comment]
This is now solved in elementary icons
