### ISSUE TITLE
Restore opened temp documents 

### ISSUE THREAD

**Issue by ctieben** [elementary/code#561]
Hi,

I had opened a temporary object (in the Firefox Cache) and after I closed Code and Firefox (in this order) I couldn't start Code any more.

I receive following message:
```
io.elementary.code -n
[FATAL 12:06:38.909219] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
[FATAL 12:06:38.909857] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
```

So it seems that Code tries to open an no existing file.
After I comment out the `window.restore_opened_documents ();` in the Application.vala file I could start Code again.

I`m not so familiar with the sourcecode to fix this on my one but hopefully someone here can help.

**Comment by jeremypw** [comment]
Closing as this has not been confirmed in the latest version of Code.  Please reopen if this issue still exists in elementary 6.1.
