### ISSUE TITLE
impossible to directly open a previously closed file from the side bar

### ISSUE THREAD

**Issue by decathorpe** [elementary/code#563]
Steps to reproduce:

1) Have a folder open in the side bar
2) Open file X by clicking on it
3) Close file X using the notebook tab's close button (this could be accidental)
4) Try to open file X again (won't work, file is already selected in the sidebar)
5) Have to open and select another file first, before file X can be opened again.

**Comment by jorgemanzo** [comment]
After some investigating (and I could be completely off the deep end with this), `Granite.Widgets.SourceList` has a `Tree` class that has a method called `set_selected()` which then calls `Gtk.TreeSelection`'s `unselect_all()`.

It would be great to have a method to call `unselect_all()` on the tree selection from the `FileView` class. That way `Document` could call this method in its `do_close()`.

Thoughts, questions or concerns?

**Comment by jeremypw** [comment]
This seems to be fixed in the current`master` branch.
