### ISSUE TITLE
UX: git branch not readable if dir name is too long.

### ISSUE THREAD

**Issue by snowparrot** [elementary/code#574]
If the dir name is too long, the git branch is too truncated or hidden.
In this case you cant see the current git branch.

Possible solution:
Have a second line just for the name of the current git branch.

**Comment by cassidyjames** [comment]
This can also be solved by #343

**Comment by jeremypw** [comment]
I would prefer the project headers to more prominent with a second line for the branch name so that it can be seen at glance without hovering for a tooltip.
