### ISSUE TITLE
Move to Trash on project folder in sidebar should not be possible

### ISSUE THREAD

**Issue by wout** [elementary/code#577]
It's not really required to be able to delete a complete project from the sidebar. Two times already I accidentally deleted a project, which will then effectively be moved to the trash.

**Comment by cassidyjames** [comment]
@wout what were you attempting to do when you accidentally trashed a project? I like being able to have some consistent actions there since a project folder is just another folder after all, and by using Trash it means the action is reversible as well.

**Comment by wout** [comment]
@cassidyjames In the meantime I moved back to Pop!_OS (where I came from), so I can't add more details. It's a shame, because I had high expectations for Juno, but the situation was unworkable for me.

**Comment by cassidyjames** [comment]
Without more details I'll have to close this. If you can provide more, we can always reopen it and try to address your concerns.
