### ISSUE TITLE
Comments in YAML are not properly color coded

### ISSUE THREAD

**Issue by wout** [elementary/code#579]
Comments in YAML files are not greyed out. Minor issue, but not ideal for legibility:

![image](https://user-images.githubusercontent.com/107324/48217693-5bccb580-e388-11e8-960e-b00aeee9f0a2.png)

**Comment by aljelly** [comment]
Probably an issue with [gtksourceview's language parsing files](https://gitlab.gnome.org/GNOME/gtksourceview/tree/master/data/language-specs) and not Code itself.

**Comment by btkostner** [comment]
Like @aljelly said, we get all of our language support from the gtksourceview language files. I would open up an issue there. Once fixed, you should see the issue resolved in most GTK text editors, including Code.
