### ISSUE TITLE
Blank sidebar after upgrade from Loki to Juno

### ISSUE THREAD

**Issue by mikelo1** [elementary/code#584]
Hi,
I'm having the same blank sidebar as explained in thread #258, but in the Juno release.
You guys can recreate the scenario if you have a Loki with the "folder manager" extension disabled in the Scratch, and then "upgrade" from Loki to Juno, running a fresh Juno installation but keeping all files in /home directory. You will find some settings missing, such as the folder manager in Code.
Since currently this feature belongs to the application core, I'm assuming that somewhere in the settings it remains disabled, and there is no option in the UI to enable it back.
Does anyone know any trick to enable it?
Thanks!

**Comment by davidmhewitt** [comment]
Can we get a screenshot of what you're seeing?

The only setting in Loki was to turn the folder manager plugin on or off. It's on all the time now and becomes active when you have a folder open.

**Comment by mikelo1** [comment]
Of course David, here you have:
![screenshot from 2018-11-16 11-46-35](https://user-images.githubusercontent.com/45094230/48616947-5b8a7680-e995-11e8-8894-68325986e643.png)

**Comment by davidmhewitt** [comment]
And what happens if you open a folder using the purple icon in the headerbar?

**Comment by mikelo1** [comment]
Clicking on the purple icon in the header bar, its opening the file browser correctly:
![screenshot from 2018-11-16 11-50-12](https://user-images.githubusercontent.com/45094230/48617232-27fc1c00-e996-11e8-964d-b17d1ccb1640.png)

**Comment by davidmhewitt** [comment]
Can you also post the output of `dconf dump /io/elementary/code/`

**Comment by mikelo1** [comment]
$ dconf dump /io/elementary/code/
[settings]
opened-files-view2=@as []
plugins-enabled=['detect-indent', 'editorconfig', 'outline']
style-scheme='solarized-light'
prefer-dark-style=false
show-mini-map=false
focused-document-view1='file:///home/XXXXXX/.local/share/io.elementary.code/unsaved/Text%20file%20from%202018-11-16%2011:05:16'
focused-document-view2='file:///home/XXXXXX/Public/buffer.txt'
opened-files-view1=@as []

[folder-manager]
opened-folders=@as []

[saved-state]
window-x=1920
window-height=605
window-state='Normal'
hp1-size=255
window-y=89

**Comment by davidmhewitt** [comment]
Thanks!

I am unsure why this is happening. The only thing I can suggest is to do a `dconf reset -f /io/elementary/code/`.

This will reset all of Code's preferences to Juno defaults and hopefully make the issue go away

**Comment by mikelo1** [comment]
Hi David,
I have tried your suggestion but the problem persists, even though I have tried the command with both session user and root user, and then rebooted the machine.
FYI, the "plugins-enabled" dconf setting remains the same:
plugins-enabled=['detect-indent', 'editorconfig', 'outline']
Thanks!

**Comment by mikelo1** [comment]
Hi David,
I just noticed that this problem is not happening only to me. It's also reproducible using the "Elementary OS 5.0 Juno" VirtualBox image available in OSBoxes. Here you have the link: 
https://www.osboxes.org/elementary-os/
Thanks,
Mikel.

**Comment by mikelo1** [comment]
Hi David,
I'ts been some days since the last update. Is there any progress on this one?
Regards,
Mikel.

**Comment by mikelo1** [comment]
Good morning David,
I've seen there was an update in the Code releases but still the problem persists.
Is there any progress on this one?
Thanks!

**Comment by cassidyjames** [comment]
@mikelo1 upgrading from Loki to Juno was not ever officially supported, and getting OS images from some third-party site is very much not supported; who knows what they've done to those images. As such, I'm going to close this issue as out of scope.
