### ISSUE TITLE
Add option to turn off 'follow last tab'.

### ISSUE THREAD

**Issue by polokasu** [elementary/code#590]

**Comment by cassidyjames** [comment]
@polokasu could you provide more information describing what you expect to happen or what current behavior is not ideal in your eyes?

**Comment by polokasu** [comment]
Need setting to deactivate the previous restoring tab when opening application (again).

**Comment by cassidyjames** [comment]
@polokasu thanks! I believe this is a duplicate of https://github.com/elementary/code/issues/473, then. If not, feel free to let me know and we can re-open this.
