### ISSUE TITLE
No explanation for green and yellow lights

### ISSUE THREAD

**Issue by snowparrot** [elementary/code#598]
If you open the directory view for dir integrated with git,
you can see changes of a file with green or yellow circle on the right side.

However it is not clear what is the exact meaning of the circle.

Possible solution: Offer a tooltip with an explaination.

**Comment by roymckenzie** [comment]
It appears that this might be a larger project requiring modification of `Granite.Widgets.SourceList` and `Granite.Widgets.SourceList.Item` to support setting tooltip text on either the tree item or the specific cell renderer item. I'm new to Gtk/Granite so maybe that is not correct.

I was able to do the following with `Granite.Widgets.SourceList.Item.badge` but it looks pretty redundant and is a waste of space. I agree that a tooltip is a better suggestion.

![Screenshot from 2019-03-10 11 24 52](https://user-images.githubusercontent.com/1065321/54089345-9beb7700-432d-11e9-919f-b33d3b5f648f.png)

**Comment by Exalm** [comment]
Similarly, the yellow and green dots can be hard to distinguish with a color blindness.

**Comment by Exalm** [comment]
See also: https://github.com/elementary/icons/issues/827

**Comment by jorgemanzo** [comment]
Tried my hand at this, feedback on the tooltip is appreciated!

![Screenshot from 2019-12-13 23-44-55](https://user-images.githubusercontent.com/26660036/70845390-f3f66300-1e02-11ea-9c8a-eaf9ac52eb00.png)
