### ISSUE TITLE
Terminal automatically "cd" to project folder in the sidebar

### ISSUE THREAD

**Issue by alvelvis** [elementary/code#600]
It would be nice if Code terminal could "cd" to a project folder in the sidebar I choose to go to. At least an option to do that when I right-click the folder would be fine!

**Comment by Mohelm97** [comment]
Hi @alvelvis 
Do think this is nice? I don't know I didn't like :D any suggestions? like editing the message or the behaviour? 
![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/1688821/49349969-05ac1300-f6a5-11e8-870c-9357b8709a54.gif)

**Comment by arshubham** [comment]
That looks great, one more thing that can be done is when opening a new folder automatically cd to that folder. Further this option can also be presented on files/folders on the sidebar.

**Comment by alvelvis** [comment]
Looks great! Not sure if I like the idea of auto-cd, it might be annoying sometimes if I just want to open a file in another folder but don't want to run a script on it.

**Comment by jeremypw** [comment]
@Mohelm97 Were you planning on providing a PR?

**Comment by Mohelm97** [comment]
@jerempw Yeaah That would be great if you have any edits please tell me, right now I haven't settled in anywhere, maybe in the next few days :D

**Comment by jeremypw** [comment]
@Mohelm97 Thanks, I hope you can progress this when you are settled.  I am used to using Geany which has a similar "Set path from document" although I would in fact more often want to navigate to the root or the build directory of the current branch regardless of the document. I certainly would not want the terminal to auto-follow the current document path.
