### ISSUE TITLE
Code does not indicate changes in document after first "save as"

### ISSUE THREAD

**Issue by ethanay** [elementary/code#603]
Reported on 3.0.1 using manual save, with "save files when changed" unchecked.

1. Open code
2. Create a new untitled document
3. Save as to create a new text file
4. Modify the document
5. An asterix does not appear by the file name in the tab after modifications.
6. The document saves correctly with a manual save, but does not indicate successful save behavior

I don't believe this is a duplicate of #381 as it does not impact the actual saving of the document

**Comment by davidmhewitt** [comment]
My unsuccessful attempts at reproducing this indicate that it's probably been fixed in the recently merged #527.

Please re-open this issue if you can still reproduce it using git `master` or once a newer version of code has been released.
