### ISSUE TITLE
[request] Add option to open code in welcome screen rather than last opened files.

### ISSUE THREAD

**Issue by mustafaREIMAHG** [elementary/code#605]
![codewelcome](https://user-images.githubusercontent.com/37519707/50057592-64798e00-0175-11e9-8fb1-a219e1eff8c2.png)

**Comment by jeremypw** [comment]
By 'option' do you mean command line option or a setting (e.g. io.elementary.code.settings.restore-tabs)

**Comment by mustafaREIMAHG** [comment]
> By 'option' do you mean command line option or a setting (e.g. io.elementary.code.settings.restore-tabs)

I mean an option that user can configure graphically form user interface (disable / enable) like the "scratch". Also the command line option would be helpful.

**Comment by cassidyjames** [comment]
Due to the discussion on #473, I'm going to consider this a duplicate of #473.

**Comment by jeremypw** [comment]
@mustafaREIMAHG :  I'm afraid my first PR to fix this was rejected as a per application setting is contrary to elementaryos design principles.  I'll submit another PR that honors the global privacy/history setting instead.
