### ISSUE TITLE
Vim emulation does not parse keystroke "a" 

### ISSUE THREAD

**Issue by mcclurgm** [elementary/code#614]
The vim emulation plugin does not appear to account for the vim `a` (insert after cursor position) command. This is often very useful, giving users more control over where the cursor goes with fewer keystrokes.

I looked at the code in [vim-emulation.vala](https://github.com/elementary/code/blob/master/plugins/vim-emulation/vim-emulation.vala) and it appears the `a` keycode is not included in the switch statements. The current code includes cases for keys `i` and capital `A` and `I` as ways of entering insert mode. A similar case could be included to handle this keystroke.

**Comment by clobrano** [comment]
As a Neovim user, I'd like to look into this.

**Comment by mcclurgm** [comment]
I also have an PR that implements this, as well as some other functionality. It's been waiting in review: #633. Not sure what we should do about the duplicate implementations then.

**Comment by clobrano** [comment]
Oh sorry, I didn't noticed. Yours look more complete, mine can be discarded

**Comment by mcclurgm** [comment]
Perhaps, but your implementation cleans the action string, which is an improvement over mine. If you do want to discard yours, then we should implement it in mine too.

I should have commented here about my PR, so sorry for that.

**Comment by clobrano** [comment]
On the other hand, I believe that merging this one, would just require a small rebase for your's to be valid as well.
