### ISSUE TITLE
Code 3.0.2 crashes on startup

### ISSUE THREAD

**Issue by AtjonTV** [elementary/code#619]
After updating Code to 3.0.2 it crashes with the following message:

```
[WARNING 20:24:07.470261] [GLib-GObject] invalid cast from 'CodeWelcomeView' to 'ScratchWidgetsDocumentView'
Segmentation fault
```

I am running ElementaryOS 5.0 Juno with all updates installed.

**Comment by jeremypw** [comment]
When does it crash?

**Comment by AtjonTV** [comment]
I temporarily resolved the issue by installing Code 3.0.1 from APT cached archives.

**Comment by AtjonTV** [comment]
@jeremypw direct on start ..

when I write `io.elementary.code` in the terminal it gives that error.

**Comment by jeremypw** [comment]
This is coming from one of the plugins - I will investigate.  To get 3.0.2 running again you will need to use dconf-editor to set key io/elementary/code/settings/plugins-enabled to the default.

**Comment by jeremypw** [comment]
The problem plugin is 'highlight-word-selection'
