### ISSUE TITLE
Zoom in on Ctrl+Equal as well

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#627]
Most browsers and interfaces that use Ctrl+/- to zoom also respond to `Ctrl`+`=`, since at least on US layouts the `+` is on the same key as `=`.

**Comment by tintou** [comment]
Already the case here, and it's on the same key

**Comment by jeremypw** [comment]
This is implemented in FIles and Photos but not in Code and Terminal so there is some inconsistency here.

**Comment by cassidyjames** [comment]
@tintou here on my US layout keyboard, I have to hold Shift in order for it to be registered as a "Plus," which is not how most apps (elementary and otherwise) seem to handle it. Most of the time Ctrl+Equals (without shift) zooms in.

**Comment by CameronNemo** [comment]
I would appreciate this.
