### ISSUE TITLE
The vim extension is unusable

### ISSUE THREAD

**Issue by mihai-dinu** [elementary/code#641]
I don't know if I'm doing something wrong or this vim extension doesn't really do much of what vim should do. 
Other than moving with the vim keys (h,j,k,l) and going in and out of insert mode (i/I), there isn't really anything else vim-like that I can do. Even so, there should be some indication that you are in insert mode or normal mode. 
Bottom line, if this is all that the extension does, it shouldn't really be called a "vim extension".

**Comment by ofperfection** [comment]
Yeah, lots of key bindings for vim don't seem to work (I use ctrl + [ instead of escape in vim), and I didn't see documentation regarding which features to expect. Also notably absent are 'o/O' for new line insertion.

**Comment by cassidyjames** [comment]
Closing since this is not really specific. Feel free to file specific, actionable issues so contributors can have something to go off of and solve.
