### ISSUE TITLE
Temporary ~ files show in sidebar

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#652]
As a side-effect of #651, temp files ending with `~` now show up in the sidebar. On the one hand this could get annoying, but on the other, these files do exist on the filesystem and could get committed to a Git project. So I'm not sure if this is an actual issue.

**Comment by berliner** [comment]
Coming from the apple world, I'd really appreciate if those files could be handled somewhere else (users tmp?) so that they neither show up for git (or any other VCS) nor in the sidebar.

**Comment by danrabbit** [comment]
Fixed in #676
