### ISSUE TITLE
Deprioritize git-ignored files

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#653]
Something Atom (and I'm sure other VCS-aware editors) does is deprioritizes git-ignored files by lowering their opacity in the sidebar. We could do something similar, or possibly even mark them as disabled in the SourceList.

**Comment by cassidyjames** [comment]
This could also supersede #652, as those files should probably be gitignored in your project anyway.

**Comment by roymckenzie** [comment]
@cassidyjames I did notice the `.git` directory is now visible, too. In VS Code the `.git` directory is hidden, even in directories that haven't been initialized with git. I created a `.git` directory manually and it doesn't appear that VS Code checks to see if it is valid. It may just check for the existence of the folder and hides it if it exists. Could implement a similar rule in Code fairly quickly I think.

**Comment by cassidyjames** [comment]
@roymckenzie is that the case for all hidden (.dot) files in a folder, or just .git?

**Comment by roymckenzie** [comment]
Just the .git folder is hidden in VS Code. Other .dot files and directories are visible.

**Comment by cassidyjames** [comment]
Fixed in #705
