### ISSUE TITLE
Use Gtk.SourceGutterRenderer to show line git diff visual cue in SourceView

### ISSUE THREAD

**Issue by roymckenzie** [elementary/code#654]
Being able to see the git diff for individual lines in a file is super helpful for determining which lines are new, modified, or removed.

There is a way to render a gutter in the `SourceView` to show specific colors on a line-by-line basis.

I've started a branch on my local for this, but before I get too involved here I wanted to open an issue and get other people's insights.

I was thinking of replicating something like this:

![Screenshot from 2019-03-12 01 48 15](https://user-images.githubusercontent.com/1065321/54183215-33a1b000-4469-11e9-99e8-9fde90586eab.png)

**Comment by cassidyjames** [comment]
GNOME Builder also does something similar, if you're looking for inspiration and design references. But I'd love to get some more @elementary/ux folks thoughts before you get too down a rabbit hole! 😁

**Comment by cassidyjames** [comment]
For context, here's what Atom and Builder do with new, deleted, and changed lines:

## Atom

![image](https://user-images.githubusercontent.com/611168/62968529-796ff500-bdc8-11e9-9a14-a6075bc8f012.png)

## Builder

![image](https://user-images.githubusercontent.com/611168/62968422-3c0b6780-bdc8-11e9-87ac-08ee9efb7b75.png)

**Comment by jorgemanzo** [comment]
I know its not October yet, but I took a shot at this feature over here https://github.com/elementary/code/pull/835

Please let me know what you think, feed back is greatly appreciated!

![image](https://user-images.githubusercontent.com/26660036/85917293-c0fb4600-b80d-11ea-8c14-79ea4e7f45fd.png)

**Comment by eyelash** [comment]
For reference:
In GNOME Builder there is a [IdeLineChangeGutterRenderer](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/3.36.1/src/libide/sourceview/ide-line-change-gutter-renderer.c) class which is a subclass of [GtkSourceGutterRenderer](https://valadoc.org/gtksourceview-4/Gtk.SourceGutterRenderer.html) which uses the abstract class [IdeBufferChangeMonitor](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/3.36.1/src/libide/code/ide-buffer-change-monitor.c) which has a concrete implementation for Git in [GbpGitBufferChangeMonitor](https://gitlab.gnome.org/GNOME/gnome-builder/-/blob/3.36.1/src/plugins/git/gbp-git-buffer-change-monitor.c)
