### ISSUE TITLE
GNOME 3.32 build failure

### ISSUE THREAD

**Issue by alucryd** [elementary/code#658]
Code fails to build following the latest GNOME release on Arch Linux, please see: https://buildbot.alucryd.xyz/#/builders/23/builds/29/steps/8/logs/stdio

**Comment by tintou** [comment]
Nothing to do with Code, if you use latest Valac, you should also update libzeitgeist to 1.0.2

**Comment by alucryd** [comment]
Oh, our zeitgeist is indeed lagging behind, thanks for the heads up!
