### ISSUE TITLE
[Request] Nim Support

### ISSUE THREAD

**Issue by bpo217** [elementary/code#659]
Add support for the Nim programming language and nimble files. 

---

Mood: Devastated.

I'm willing to contribute!

**Comment by tintou** [comment]
Thanks for the issue.
We are using GtkSourceView here, the same component as GEdit, you can download the .lang file from https://github.com/nim-lang/Aporia/blob/master/share/gtksourceview-2.0/language-specs/nim.lang and put it inside of ~/.local/share/gtksourceview-3.0/language-spec/
If you feel that this should be available out-of-the-box feel free to open an issue on GtkSourceView itself https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by ITwrx** [comment]
i doubt that lang file will still work, but assuming it did, is this still the correct location to place it for Code to find it? I just saved it there, and restarted code, and Nim is not available in the syntax highlighting select.
thanks

**Comment by ITwrx** [comment]
In case any other nim users come across this issue: 

[nim.lang](https://raw.githubusercontent.com/StefanSalewski/NEd/master/nim.lang)
[nimdark1.xml](https://raw.githubusercontent.com/StefanSalewski/NEd/master/nimdark1.xml)

Copying the two linked files above to /usr/share/gtksourceview-4/language-specs/ and  /usr/share/gtksourceview-4/styles/and restarting Code enabled Nim syntax highlighting in my Fedora 39 with gtksourceview4 installed. I don't know if it's perfect yet, but so far, so good. 

Thanks for Code!
