### ISSUE TITLE
Scroll to cursor when pasting

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#668]
Right now if you copy something up above, then paste it while the cursor is out of view, it's easy to paste without any visual feedback. Instead, we should scroll to where the cursor is when pasting. This is the behavior in Atom, Sublime, and VS Code at least.

**Comment by davidmhewitt** [comment]
I can't confirm this. Code scrolls to bring the newly pasted text into view on my machine. Do you have any further steps to reproduce this?

**Comment by cassidyjames** [comment]
@davidmhewitt open a new document, type "test" at the top and copy it, press "Enter" a bunch so "test" is off-screen above, leave the cursor down at the bottom, scroll back up with the mouse, and then hit Ctrl+V. In my case, it pastes it down below but doesn't scroll down. It's possible this is supposed to be handled in Gtk and/or SourceView itself, and I'm seeing some strange bug there? But I'm able to reliably reproduce it.

**Comment by cassidyjames** [comment]
@davidmhewitt ah, when using the context menu to paste, it does scroll down. But not when using the shortcut. That's… strange.

**Comment by cassidyjames** [comment]
@davidmhewitt in testing this more, it seems like _sometimes_ it scrolls down, but sometimes it does not. I think it might be related to the scroll inertia; if I scroll up and hit Ctrl+V immediately, it does not scroll down on paste. If I scroll up, wait a second, then paste, it does scroll down. So this is likely something strange in Gtk itself with how the inertia is being handled, and it's not supposed to scroll-on-paste while the user is scrolling or something.

As such, I'll close this. :smile:
