### ISSUE TITLE
How can i use C libraries in Vala? Or how to use g-ir-scanner?

### ISSUE THREAD

**Issue by FlightBlaze** [elementary/code#678]
How can i use C libraries in Vala? As written in [GNOME documentation](https://wiki.gnome.org/Projects/Vala/Bindings), I need to scan my C headers by command line tool [g-ir-scanner](http://manpages.ubuntu.com/manpages/trusty/man1/g-ir-scanner.1.html) to generate *.GIR file and then generate VAPI (Vala API) file with $ vapigen --library MyLibrary MyLibrary.gir to use in Vala.

Everything is clear except using [g-ir-scanner](http://manpages.ubuntu.com/manpages/trusty/man1/g-ir-scanner.1.html). How to use this tool?

Or how to create bindings without this tool? Use ready [vapi from collection](https://gitlab.gnome.org/GNOME/vala-extra-vapis) is not solution

**Comment by davidmhewitt** [comment]
This repository is for the elementary code editor and should not be used for general support/programming questions. Slack and Stackoverflow are better for these type of questions.

`g-ir-scanner` can not be used for any library, only libraries that have been written in GObject style C. If the library is not written in GObject C, then you will have to write a binding manually. See https://wiki.gnome.org/Projects/Vala/ManualBindings

If the library is GObject C, then `g-ir-scanner` is typically integrated into the build system and a `.gir` file and often a `.vapi` file are generated when the library is built. See examples for [autotools](https://gi.readthedocs.io/en/latest/buildsystems/autotoolsintegration.html) and [meson](https://gi.readthedocs.io/en/latest/buildsystems/meson.html).
