### ISSUE TITLE
Incorrect relative path

### ISSUE THREAD

**Issue by GBoux** [elementary/code#688]
When I use `cd` to navigate in my directories, and then using `io.elementary.code ./foo.txt`, Code always opens ~/foo.txt (the one in my home directory) instead of the foo.txt in my current directory.

**Comment by jeremypw** [comment]
I cannot reproduce this using Juno stable or Juno master, with default settings.  Please give more details regarding your setup.  Note Code will restore previously open documents as well as the one specified. It will not open a document already open but only if the uris match.

**Comment by GBoux** [comment]
Sorry, I forgot 1 step : first, I open Code not using the command line, but using the button in the Applications menu.
Then, while Code is still opened, the problem I described on previous post occurs.

And now I've try something else :
I don't open Code from the menu, I use the terminal, I go in a directory `cd A/` and open a file `io.elementary.code ./foo1.txt`. It works.
Then, without closing Code, I open a new terminal and go in another dirctory `cd B/`. I open another file `io.elementary.code foo2.txt`. It doesn't open the file ~/B/foo2.txt but the file ~/A/foo2.txt
The current path is set when you open the application, and it's not refreshed each time you run the command.

I think this can be corrected by a simple script, replacing the `./foo2.txt` by `$(pwd)/foo2.txt` before sending it to Code.


ps : I'm using Elementary OS 5.0 Juno, based on Ubuntu 18.04.2 LTS, Ubuntu 18.04.2 LTS, Gtk+ 3.22.30

**Comment by jeremypw** [comment]
OK, confirmed with revised steps.
