### ISSUE TITLE
Code occasionally saves files as blank

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#698]
Similar to the behavior I was seeing with #305, but still happens when I disable the plugin. It seems that if I have a particularly large/complex file (several hundred lines, lots of syntax highlighting), sometimes when Code saves it (automatically or with Ctrl+S), the file on disk is overwritten with an empty version. However, the SourceView within Code retains the code, and making a trivial change (like whitespace) correctly re-saves the entire file.

**Comment by cassidyjames** [comment]
Specifically I keep seeing this with this file:

https://github.com/elementary/blog/pull/27/files

While editing, Jekyll regenerates based on a blank file. I've also had this happen with code in Ephemeral, ending up committing an empty version of the file. :grimacing:

**Comment by jeremypw** [comment]
Closing as test file no longer available. Please re-open if still experiencing with latest version and have a test file available.
