### ISSUE TITLE
Need of a Word processor

### ISSUE THREAD

**Issue by ghost** [elementary/code#704]
I always loved how elementary OS comes with most of the basic things you need in a OS without having to install much else. The only thing I feel it's really lacking is a proper word processor. I know "code" is an option but it doesn't feel like a basic word processor, it feels like it's for just what it's titled, coding. And I may be mistaken but doesn't seem like it has an option to print either. I think a very simple word processor separate from code would be a great edition to elementary OS and help it feel a little more complete. Doesn't have to be feature rich but just enough to write simple documents, change fonts, letter size, maybe ability to add images to it and print. Sorry if I put this request in the wrong section, not sure where else to put it.

**Comment by jeremypw** [comment]
This probably best filed here: https://github.com/elementary/os/issues

You are right that Code is intended principally for coding and other plain text tasks, not word processing.

Developing a word processor from scratch is no small undertaking but if there were a suitable project preferably already written in Vala and a person willing to maintain an "elementary-fied" version of it I suppose it could happen ,...

**Comment by jeremypw** [comment]
Closed as out of scope.
