### ISSUE TITLE
Cannot save settings as root

### ISSUE THREAD

**Issue by d-packs** [elementary/code#729]
## Describe the bug
When runnig code as sudo the settings cannot be changed.

If applicable, add screenshots or screen recordings to help explain your problem.

### To Reproduce
1. Launch the program by typing `sudo io.elementary.code` or `sudo -b io.elementary.code`
2. Click on 'Settings'
3. Try to change any of the settings
4. The settings cannot be changed

### Expected behavior
Most programs have separate settings profiles for users and root, so expected behavior would be to be able to change settings for root as it is possible for particular users.

### Screenshots or screen recordings

![Screencast2019-11-13124802](https://user-images.githubusercontent.com/33980111/68757602-df148d00-0614-11ea-9557-44a6ebb2f7d8.gif)

## Platform Information
OS: Arch Linux x86_64
Kernel Release: 4.19.83-1-lts
WM: Xfwm
DE: Xfce 4.14
RAM: 4417 MB / 11631 MB
Processor Type: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz

Code version: 3.1.1

**Comment by tintou** [comment]
We do not support running any of our software with `sudo`

**Comment by d-packs** [comment]
How do you edit root owned files like configs then?

**Comment by tintou** [comment]
You can copy the file and paste it once edited or continue to use the terminal.

**Comment by d-packs** [comment]
I see. No future plans to support this?

**Comment by tintou** [comment]
No, as running a graphical application with `sudo` won't even work with any Wayland application in the future.
We might want to introduce support for the `admin:///` GVFS scheme but we don't have any plan for it for now

**Comment by danrabbit** [comment]
Closing because this is out of scope. You should never run graphical applications with `sudo`. As a stop-gap for editing root-owned files you can use `pkexec`
