### ISSUE TITLE
Does not save files via FTP/SFTP

### ISSUE THREAD

**Issue by beretar-tg** [elementary/code#730]
When you open a file via FTP, you cannot save it.
Error: «You can not save this file»
If you open it in Sublime Text or another editor, the file is saved.

**Comment by jeremypw** [comment]
This issue seems to go back a long way - see #3 for example.

**Comment by kaixoo** [comment]
If still valid, high priority

**Comment by jeremypw** [comment]
Looking at #3 it seems that this not a current problem or at least not a Code problem - if gvfs reports the file as writable it should save. I am therefore going to close for now.
