### ISSUE TITLE
Preferences: Swap "Draw spaces" combobox for "Visible whitespace" switch

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#732]
Follow-up from https://github.com/elementary/code/pull/722#issuecomment-547048283.

>Design-wise, since we've moved from a ternary option to a binary one, we could also revisit how it's displayed. My thought is to just expose it as "Visible whitespace" with a switch: on is "Always," and off is "For Selection".

**Comment by igordsm** [comment]
@cassidyjames Like this?
![Screenshot from 2021-10-04 20-13-47](https://user-images.githubusercontent.com/221446/135936829-9c9e2035-33a6-4a30-bd01-b917543b611d.png)
