### ISSUE TITLE
How to open code in terminal

### ISSUE THREAD

**Issue by Yakumo-Yukari** [elementary/code#750]
Is there a simpler command than io.elementary.code?

**Comment by cassidyjames** [comment]
There is not currently, as the intent is to RDNN all package names and binaries, as covered here. https://medium.com/elementaryos/cleaning-up-app-codenames-ef9fc637ddef

What I personally do is create an alias for `code` to `io.elementary.code` but that wouldn't work well for anyone who has installed Visual Studio Code as they assume nobody else would want to use the word "code" for a binary. :stuck_out_tongue:
