### ISSUE TITLE
Sidebar doesn't remember to stay close on re-open

### ISSUE THREAD

**Issue by KorbsStudio** [elementary/code#757]
#89  Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
When working on only one file, I keep the sidebar closed. But does not stay close when re-opening Code.

### To Reproduce
1. Click on the gear icon in titlebar
2. Click on **Toggle Sidebar**
3. Close Code
4. Re-open Code

### Expected behavior
Closing sidebar, closing Code, on re-open the sidebar should not be opened

### Screenshots or screen recordings
https://i.imgur.com/WIE3SmR.gifv

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
There is no setting for saving the open/closed state of the sidebar.  If there are folders open in it, it will open on start up.  Not sure if that is an oversight or intended so that the user does not forget about it.

Should be simple enough to add a setting if desired.

**Comment by rajitsingh** [comment]
This issue has reappeared after the latest stable update to Code version 3.4.1. 

I have no folders opened in the sidebar and don't use it, so I keep it toggled off. The state of the sidebar toggle does not persist across application restarts. Even if I manually toggle it off, it appears again when the application is closed and launched again.

**Comment by jeremypw** [comment]
The PR that fixes this has not yet been approved and merged I am afraid.
