### ISSUE TITLE
Underscores are not counted as part of the word when double clicking words in the search bar 

### ISSUE THREAD

**Issue by aljelly** [elementary/code#759]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

In the main editor, double clicking, say, `word` in `my_word` selects the whole of `my_word`. This is useful for variables. However, in the search bar, double clicking `word` in `my_word` selects only `word`. It'd be nice if it were consistent with the main editor.

**Comment by Marie-Joseph** [comment]
This is true of all Gtk entryboxes. I'm not a maintainer, but my personal advice would be to report this over on Gtk's bug tracker. I also find it annoying, and not just in Code.

**Comment by danrabbit** [comment]
Yes, as @Marie-Joseph has pointed out, this should be reported against Gtk on GitLab. Closing as "Out of scope" since the problem can't be solved in Code itself
