### ISSUE TITLE
Close associated files when closing a project

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#774]
It feels like it would keep things cleaner to close any open files for a project when closing that project.

**Comment by igordsm** [comment]
Hey @cassidyjames , I started a prototype on this one. When closing a folder only files that were opened by clicking in `FolderManager.FileView` on that folder are closed. Files that were opened using "Open" are not, even if they do belong to the closed folder. 

Right now files are always closed. Should we ask for confirmation? Any input on this @cassidyjames ?

I am preparing a PR for this and will submit it later this week.

**Comment by jeremypw** [comment]
This was implemented by #912
