### ISSUE TITLE
Scroll past end of file

### ISSUE THREAD

**Issue by HImichun** [elementary/code#799]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
Working at the end of a file may be uncomfortable for some users. I prefer the line I'm working on to be in the centre of the screen. Having an option to scroll beyond the last line would make experience much better. Without such feature I often have to resort to adding many empty lines to the end of the file, which just doesn't feel right.

![image](https://user-images.githubusercontent.com/16974379/80399688-48861080-88c2-11ea-9bbf-87e4d293c4db.png)

**Existing work**

This feature exists in many editors such as Visual Studio Code (on by default), Atom, Notepad++, etc.

Scrolling beyond last line in VSCode:
![image](https://user-images.githubusercontent.com/16974379/80399948-bd594a80-88c2-11ea-8ae8-bd840aebb370.png)

**Comment by cassidyjames** [comment]
My guess is that this would need to be implemented in GtkSourceView itself, but I'm not sure.

**Comment by cassidyjames** [comment]
As a note, it looks like VS Code allows scrolling all the way until the last line of the file is the very top line of the view. Atom keeps three lines on screen. If we wanted to do something similar, just CSS wouldn't work, as we'd need to know how many lines-tall the screen is (and vh doesn't work in GtkCSS).

**Comment by jeremypw** [comment]
You need to set the "bottom_margin" property on the the SourceView.
