### ISSUE TITLE
Full file path is currently not obtainable; would be useful to show in mouse-over pop-up.

### ISSUE THREAD

**Issue by sillyrat** [elementary/code#804]
Hello! Other text editors (such as Geany) show the full path of the file being edited when the mouse passes over that file's tab; but in Code, all I see when I mouse-over a tab is the exact same filename that's already displayed on the tab. I've been using Code only for a short time, yet have already run into several instances when I was unsure of exactly where the file in a particular tab had been loaded from (particularly if Code had restored the tabs from the previous session). This issue is compounded by the nature of the Save As dialog, which does not default to opening where the original file was located (which would be tremendously useful). I've been through all the preferences, dug around with dconf-editor, and generally tried my best to see if I had something set up wrong, but apparently not. Could you add a preference to show the full-path filename in the mouse-over pop-up? Thanks for your consideration of this issue!

**Comment by jeremypw** [comment]
I think this is because the Granite.DynamicNotebook does not currently expose the tab tooltips (so Files and Terminal have the same issue) so probably needs an update to Granite first.
