### ISSUE TITLE
Sidebar shows incorrect project structure

### ISSUE THREAD

**Issue by gechandesu** [elementary/code#818]
## Describe the bug

Information about the project folder is not updated or an incorrect update occurs while the application is running. When you restart Code, the bug disappears.

### To Reproduce
1. Open the project folder in Code.
For example I've opened `/home/gd/folder` with structure:
```
├── some file
└── subfolder
    └── new file.txt
```
2. Then I renamed this folder to `folder_2` and created new empty directory named `folder` in same path.
3. Sidebar was updated. See bug:
![bug](https://imgur.com/Gvsui9r.png)
I've expanded the folders.

4. If I add new files, then the old folder partially duplicates the structure. Shown also in video below.
![Imgur](https://imgur.com/iMxM7zk.png)

### Screenshots or screen recordings
[https://vimeo.com/420500030](https://vimeo.com/420500030).

## Platform Information
* elementary OS 5.1.4 Hera
* Code 3.4.0
- [ ] I'm using the latest version from git that I've manually compiled
- [ x] I'm using the latest released stable version

**Comment by Otofuji** [comment]
Hello! I have tried and reproduced this bug here. I have investigated the reason and it is in error handling in ProjectFolderItem. I'm preparing a pull request to address this issue.
