### ISSUE TITLE
Notebook tabs do not change with theme selection

### ISSUE THREAD

**Issue by zeebok** [elementary/code#831]
When changing the theme, the tabs for notebook of open files does not change with it. Restarting Code does update it to all the right theming.

![Screenshot from 2020-06-23 22-07-55@2x](https://user-images.githubusercontent.com/1378344/85489445-00bbf680-b59e-11ea-8c58-f6a0294a00da.png)

### To Reproduce
1. Open files
2. Change the theme

### Expected behavior
The whole UI should change theme when selecting a different theme

### Platform Information
 - elementary OS
 - Juno

**Comment by cassidyjames** [comment]
I also noticed this recently. Not sure what has changed.

**Comment by zeebok** [comment]
This must be fixed in some update because I am no longer seeing this behavior. If anyone else can confirm, I'll close this.

**Comment by cassidyjames** [comment]
Ah yep, this was addressed in https://github.com/elementary/code/pull/1028
