### ISSUE TITLE
Use CSS to set font style

### ISSUE THREAD

**Issue by danrabbit** [elementary/code#847]
`Gtk.Widget.override_font` is deprecated

It looks like Dazzle has a method `dzl_pango_font_description_to_css` that would make this easier

**Comment by jeremypw** [comment]
Do you mean to make libdazzle a dependency or to port just that function?

**Comment by danrabbit** [comment]
@jeremypw could do either, I suppose. I'm not sure if we're currently using Dazzle anywhere else for anything else. Epiphany might pull it in maybe?
