### ISSUE TITLE
WYSIWYG-like keyboard shortcuts in Markdown

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#850]
When editing a Markdown README file or blog post, it would be handy to be able to use some familiar/standard WYSIWYG or word-processor-like keyboard shortcuts for text formatting:

- Ctrl+B for bold (`**strong**`)
- Ctrl+I for italic (`_emphasis_`)
- Ctrl+K for link (`[text](url)`)

For a great implementation, pressing the key should insert the characters and put the cursor where the user would most likely type next (i.e. between the `**` or `_`, or in the `[]` of a link), while hitting the shortcut with selected text should wrap the text with the formatting characters. This is how GitHub—which users of Code are likely to be familiar with—handles it in their Markdown inputs. 

This might be best implemented in an optional plugin.

**Comment by igordsm** [comment]
I would like to work on this. Besides these shortcuts, how about using Ctrl+1 (up to Ctrl+6) for headings?

**Comment by cassidyjames** [comment]
I'm not sure if those would conflict with anything else, like changing tabs. I think the listed ones would be a good start, and we can always expand.

**Comment by igordsm** [comment]
So it seems like Ctrl + i is taken for *Go to Line*. I implemented using Ctrl+Shift+I and it works fine.
