### ISSUE TITLE
Save selected line with state

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#860]
I noticed it looks like Gedit does this, and it's super handy to be able to jump back to whatever line you were previously on.

**Comment by tintou** [comment]
As an implementation PoV for the person reading this, please do not use GSettings for saving this. Something like a keyfile in session .config or .cache is the way to go.

**Comment by cassidyjames** [comment]
@tintou could you share the reason _why_ so folks can better learn/understand?

**Comment by tintou** [comment]
GSettings is not made for state saving but only for Preferences, the whole machinery isn't made for intensive caching of states. We are already abusing it with our window state saving. Saving the selected line for each opened document would result in a lot of data being loaded/saved in opening and closing state.

**Comment by jeremypw** [comment]
That being so, perhaps we need to provide guidance on https://developer.elementary.io/ how to do this, or even provide some Granite components to assist?  We do not want people reinvneting the wheel or inventing lots of different wheels.  The only example of saving state on https://developer.elementary.io/ uses GSettings (throttled).

**Comment by danrabbit** [comment]
This was fixed in #966
