### ISSUE TITLE
persistency with the sidebar status

### ISSUE THREAD

**Issue by yaolet** [elementary/code#864]
I usually prefer sidebar on the code application closed since i am working with a small screen, but it seems that the app does not remember this preference.  Every time it relaunches, the left sidebar is on by default, which is a tad painful. 

Would you kind people @ elementary consider making such choice persistent?

Thanks in advance.

**Comment by davidmhewitt** [comment]
Duplicate of https://github.com/elementary/code/issues/861

This has already been resolved and will be released in the next update to Code.

Thanks for your report.

**Comment by nevillepark** [comment]
Hi, a new update has not been released yet, and this bug is annoying. Is there a way to downgrade Code or install an older version that does not have the sidebar, without having to compile it myself?
