### ISSUE TITLE
Consider removing browser preview extension

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#867]
While this non-default extension can be handy in some limited cases where you're editing a self-contained HTML file, modern web development has long moved away from that paradigm. It feels like these days shipping an entire browser inside of Code is Not a Good Idea, unless it could be aware of all kinds of web frameworks and be far, far smarter than it is today. 

I think the best course would be to remove it unless/until someone wants to develop _and maintain_ something else—but even then, just use your favorite web browser and tile it side-by-side…

**Comment by danrabbit** [comment]
Yeah I'm in favor of removing this. I highly doubt that it's actually used
