### ISSUE TITLE
Add keyboard shortcuts to swtich tabs

### ISSUE THREAD

**Issue by mcclurgm** [elementary/code#903]
## Problem

It would be nice to be able to switch tabs without leaving the keyboard.

## Proposal

There are 2 standard shortcuts I know of for this. Firefox, Epiphany, etc use `ctrl + PgUp/PgDn`, Safari and other Mac apps use `ctrl+tab` and `ctrl+shift+tab`.

**Comment by cassidyjames** [comment]
I could have sworn we supported Ctrl+Tab. Huh. Yeah I agree this should be here.

**Comment by jeremypw** [comment]
`ctrl+tab` and `ctrl+shift+tab` are already taken by the editor, so we need alternatives.

**Comment by jeremypw** [comment]
Ctrl-Tab and Shift-Control-Tab works for me in master.

**Comment by cassidyjames** [comment]
Ah yeah my bad, I forgot I was on Hera at the moment, lol. @mcclurgm so this has been solved in the codebase and will be released with elementary OS 6.0.
