### ISSUE TITLE
Add whole word search

### ISSUE THREAD

**Issue by mcclurgm** [elementary/code#933]
## Problem

Especially when there's no way to search for specific symbols, it's often useful to search for an exact term when writing code. This is a term that's bounded on either side, and doesn't match if there's more non-space text on either side of the term. For example, say I have a variable called `foo` and a function `do_thing_to_foo`. If I want to find where in my code `foo` is used, I would use a whole word search to find instances of the variable. Without this feature, I would also have to deal with every other place in my code that the word `foo` appears, including declaring and calling the function.

## Proposal

Similar to how we have the case-insensitive option in the search bar, it would be great to have a button for word bounded search.

## Prior Art

Here's an example in VS Code (the button with the bars above and below the Ab):
![Screenshot von 2021-01-30 08 39 46](https://user-images.githubusercontent.com/29022469/106360994-bdb2c600-62d8-11eb-8c4b-982add23e908.png)

**Comment by simonkrauter** [comment]
I miss this option too.
Notes:
In Mousepad it's called "Match whole word".
In gedit it's called "Match entire word only".

**Comment by jeremypw** [comment]
As a workround you can insert spaces in the search term e.g. searching for " foo " will exclude `do_thing_to_foo` (but not `foo ()`). Could also use a regex search.  But yes, a button would be much easier.

**Comment by jeremypw** [comment]
Added "Needs Design" for design team input regarding how this should be exposed.  Space is short in the searchbar as we need to be able to half-tile the window on a minimum recommended resolution screen.
