### ISSUE TITLE
Can't add .hidden folder to sidebar as project folder

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#936]
## What Happened

I have a .dotfiles repo, and having a .github repo is common to set up org-wide settings. When I try to add one of these folders to the sidebar, they don't appear.

## Expected Behavior

.hidden folders should show as top-level project folders, like any other project folder.

## Steps to Reproduce

1. Create a hidden folder beginning with a `.` character, i.e. `.github`
2. Open it with Code, either via the CLI or GUI
3. See that it doesn't show in the project sidebar

## Platform Information

elementary OS 6 Early Access

**Comment by jeremypw** [comment]
At the moment Code deliberately ignores hidden files - it is easy to change that to always show them.  A further question is do we want to provide a toggle for showing/hiding them e.g. in the project context menu?

**Comment by cassidyjames** [comment]
@jeremypw I think it makes sense to hide them by default beneath a project folder. However, my issue is specifically about not being able to add a hidden folder as a top-level project folder; it currently just silently fails.

**Comment by jeremypw** [comment]
@Ah, I misunderstood - sorry.  I hadn't come across hidden repos before.

**Comment by jeremypw** [comment]
Of course, if you have a hidden project folder, then all its children are hidden so you have to be able to show hidden subfolders anyway.  So the default behaviour would have to be overridden for hidden project folders.

**Comment by dar5hak** [comment]
> But presumbly there is a case for accessing a hidden folder like .github within a project folder to edit workflows etc?

Yes. Now that people will start porting apps to Flatpak, they might also want to add Bilal's flatpak-builder action. That was my use case anyway.

Currently the only way (that I know) to edit a workflow is to open its YAML file directly from **Open a file** option and locate it in the file chooser, which is kinda tedious.

Shall I open a new issue for this?

**Comment by jeremypw** [comment]
@dar5hak Yes, please open a new issue and describe the solution you envisage bearing in mind @cassidyjames says hidden subfolders of a normal folder should not be shown by default. I guess that we either special case certain folders like `.github` or add a "Show Hidden Folders" option to the project folder context menu.
