### ISSUE TITLE
Cannot reopen last document when it is already selected in the sidebar

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#972]
## Steps to Reproduce
1. Close all documents but have a project folder open
2. Click on a (non-selected) item in the sidebar - document opens
3. Close the document using the notebook tab - corresponding item remains selected in sidebar
4. Click on the selected sidebar item - nothing happens

## Expected Behavior

Clicking on a sidebar item should always open the document if it is not already opened, even if the item is already selected (and/or on closing a document its bookmark should always be deselected).

## Platform Information

Elementary 6.0 daily

**Comment by kaixoo** [comment]
I think this should be priority medium at least. It is pretty annoying and has been a problem since 6.0.

**Comment by jeremypw** [comment]
#1465 may have fixed this - needs to be checked.

**Comment by jeremypw** [comment]
Looks like is fixed now - the steps to reproduce given no longer produce the bug.
