### ISSUE TITLE
fails to build (on Fedora) since PR 951 (pkexec support) was merged

### ISSUE THREAD

**Issue by decathorpe** [elementary/code#973]
Starting with #951 , code fails to build on all current Fedora releases (from 32 to 35/rawhide), with an error about missing translation files:

```
+ /usr/bin/meson compile -C x86_64-redhat-linux-gnu -j 2 --verbose
ninja: Entering directory `x86_64-redhat-linux-gnu'
[...]
[6/134] /usr/bin/meson --internal msgfmthelper data/io.elementary.code.policy.in data/io.elementary.code.policy xml /builddir/build/BUILD/elementary-code-3.4.1+git210311.193015.d07b72e9/po/extra
FAILED: data/io.elementary.code.policy 
/usr/bin/meson --internal msgfmthelper data/io.elementary.code.policy.in data/io.elementary.code.policy xml /builddir/build/BUILD/elementary-code-3.4.1+git210311.193015.d07b72e9/po/extra
msgfmt: cannot locate ITS rules for data/io.elementary.code.policy.in
[...]
ninja: build stopped: subcommand failed.
```

Not sure how it's possible that this affects all Fedora releases but not elementary OS.

The only difference I could think of is that on elementary OS, you might use a different name for the "build" directory - on Fedora, we use the target triple `x86_64-redhat-linux-gnu` (of course, different, depending on the target architecture) as the name for the build directory.

**Comment by tintou** [comment]
You need a build-dependency on `polkit-devel` as it is the package providing the .its file.

**Comment by decathorpe** [comment]
Thanks, that fixed it. But shouldn't that dependency be added to meson.build if it fails with an obscure error without it (i. e. a `dependency('polkit-agent-1')`)?

**Comment by tintou** [comment]
We don't have any binary dependency so it doesn't make sense to add this, there is no warranty that the its file will be with polkit-agent-1 development files either.
The error was:
```
/usr/bin/meson --internal msgfmthelper data/io.elementary.code.policy.in data/io.elementary.code.policy xml /builddir/build/BUILD/elementary-code-3.4.1+git210311.193015.d07b72e9/po/extra
msgfmt: cannot locate ITS rules for data/io.elementary.code.policy.in
```
Which isn't really that obscure :wink:

**Comment by landv** [comment]
> 
nice！finally solved the problem。thank you very much。3Q
`FAILED: data/io.elementary.code.policy `
`/usr/bin/msgfmt: 无法定位 data/io.elementary.code.policy.in 的 ITS 规则`
`msgfmt: cannot locate ITS rules for data/io.elementary.code.policy.in`
You need a build-dependency on polkit-devel as it is the package providing the .its file.

到此一游~
A visit~
