### ISSUE TITLE
Search box doesn't allow non-English characters to be entered when using Fcitx + Mozc

### ISSUE THREAD

**Issue by atsuya** [elementary/code#977]
## What Happened
When I try to search texts in Code using the search box (I trigger it to show up by pressing Ctrl+F), it doesn't allow entering non-English characters. To be specific, I tried with Japanese (I use Fcitx + Mozc).

On other GTK apps, a text field shows a Japanese character when I type (with my Japanese input method is enabled), however, the search box on Code shows an English character instead (the English character that corresponding to what I typed as I use English keyboard to type Japanese).

I actually don't know if this started to happen or has been like this as I never tried to search texts in Japanese on Code before.  

## Expected Behavior
The search box on Code should allow searching by non-English characters.

## Steps to Reproduce
1. Launch Code.
2. Press Ctrl+F to bring up a search box.
3. Enable non-English input method and type some non-English characters in the search box.
4. Observe that non-English characters do not get entered in the search box. 

### Logs
N/A

## Platform Information
From System Settings > About:
- elementary OS 5.1.7 Hera
- Built on Ubuntu 18.04.4 LTS
- Linux 5.4.0-70-generic
- GTK 3.22.30

Let me know if you need addition info. Thanks!

**Comment by ryonakano** [comment]
Thank you for your report. FYI I don't see this issue with ibus-mozc, but I'll check if I can reproduce it with fcitx later. Just one thing I want to confirm; do you see the issue only when searching and can you type Japanese in the main text field normally?

**Comment by atsuya** [comment]
Hi Ryo,

You are correct; I can type Japanese in the main text field without any problem. I can't just for the search box.

That's great to hear that ibus-mozc works as it at least means there is a workaround.

**Comment by atsuya** [comment]
I tried this with ibus-mozc, and I confirm I can enter non-English characters on the search box ([this blog post](https://magidropack.hatenablog.com/entry/2019/01/05/174048) was very helpful to get ibus-mozc working).

**Comment by atsuya** [comment]
I suppose there are more users using Fcitx than IBus (not sure about it on elementary OS though), so I keep this bug open. However, as IBus is the default for elementary OS, you can close this bug if that's better for bug management point of view.

I also updated the title to indicate that this is about when Fcitx + Mozc is used.

**Comment by jeremypw** [comment]
Ibus (including ibus-mozc) will be much easier to setup on Elementary 6 :grin:

**Comment by ryonakano** [comment]
Hi @atsuya, sorry for late reply. I prepared the latest Hera in my vm and tried to reproduce your issue but I can't. The search box accepts Japanese characters using fcitx-mozc:

![fcitx in code](https://user-images.githubusercontent.com/26003928/115318663-25323080-a1b9-11eb-9852-29a612fd9603.png)

What I did to activate fcitx-mozc is:

```
$ sudo apt install fcitx-mozc
$ im-config -n fcitx
```

**Comment by atsuya** [comment]
No worries.

What if you have English as your system language, meaning the UI is shown in English?

**Comment by ryonakano** [comment]
Ah, so you mean your system language is not Japanese but English? I'll check what happens if system language is English.

**Comment by atsuya** [comment]
Correct. I'm not sure if that would result in a different outcome, but I use English as system language.

**Comment by ryonakano** [comment]
Hmm, I changed the system language to English but still can't reproduce your issue… :sweat:

![2](https://user-images.githubusercontent.com/26003928/115384779-630f7300-a212-11eb-8420-83c55151c6da.png)

**Comment by atsuya** [comment]
I see. It could be just me. I'll close this one.

Thanks for your support, Ryo!

**Comment by ryonakano** [comment]
Alright, I hope your issue get resolved at some point!
