### ISSUE TITLE
Sidebar keeps coming back

### ISSUE THREAD

**Issue by VladRossenko** [elementary/code#982]
## What Happened
The sidebar keeps coming back every time I reopen the app even though I toggled it to be hidden.

## Expected Behavior
When I click "Toggle Sidebar" to hide the sidebar, I expect it to stay hidden until I specifically want it back again, instead it keeps coming back every time the app is relaunched.

## Steps to Reproduce
Click "Toggle Sidebar" or `Ctrl` + `Backslash` to hide the sidebar, then reopen the app.

## Platform Information
Elementary OS 5.1.7 Hera

**Comment by jeremypw** [comment]
There is a setting which remembers the sidebar visibility and this must have worked at one point so this looks looks a regression.

**Comment by davidmhewitt** [comment]
This has been fixed and continues to work in the Odin daily builds, but a version of code that has this feature has not been released to 5.1.7.

See #757 and #842

**Comment by jeremypw** [comment]
I am seeing this on Odin 6.0 daily so it appears to have regressed again - working on a fix.

**Comment by jeremypw** [comment]
Actually, it only occurs when the Outline plug (or any plug adding a second tab to the sidebar stackswitcher) is open - with only one tab then the visibility is restored properly.
