### ISSUE TITLE
A method to indicate the current project

### ISSUE THREAD

**Issue by danrabbit** [elementary/code#991]
## Problem

Some more advanced IDE features require us to know which project we're currently working in to function in a predictable manner. Global search, build & run, git features, etc. At the moment, we have no clear way of doing this.

## Proposal

- [ ] Add a dropdown to the headerbar to manage and select projects
- [ ] Only list files and folders from the selected project in the sidebar
- [ ] Remove items that no longer make sense like "close other folders"

This would automatically close:
* #568

![image](https://user-images.githubusercontent.com/7277719/115475669-005bae80-a1f5-11eb-8aa4-eee251a40254.jpeg)

**Comment by jeremypw** [comment]
At the moment git actions are on the context menu of the project folder so would be expected to apply to that project.  However, moving some actions to the headerbar would make them more convenient but require an "active project" concept.

One possibility would be to limit only one project per window - if you require two projects open (which can be useful for comparison, copying code etc) then it would be opened in a new window.

It feels a bit odd to not list files in the sidebar if they are opened in the notebook. Maybe they could be in a "Other Files" section?
