### ISSUE TITLE
data/meson.build:35:0: ERROR: Tried to assign an invalid value to variable.

### ISSUE THREAD

**Issue by yonas** [elementary/code#999]
## What Happened
1. Installed dependencies.
2. Ran meson.
3. Got an error.

## Expected Behavior
I shouldn't get this error.

## Steps to Reproduce

1. Install dependencies:

- libeditorconfig-dev
- libgail-3-dev
- libgee-0.8-dev
- libgit2-glib-1.0-dev
- libgtksourceview-4-dev
- libgtksourceview-3.0-dev
- libgtkspell3-3-dev
- libgranite-dev
- libhandy-1-dev
- libpeas-dev
- libsoup2.4-dev
- libvala-0.48-dev
- libvte-2.91-dev
- valac

2. Run build:

> meson build --prefix=/usr

### Logs
[meson-log.txt](https://github.com/elementary/code/files/6388884/meson-log.txt)

## Platform Information

- Ubuntu 20.10 (Groovy Gorilla)
- Linux desktop 5.8.0-50-generic #56-Ubuntu SMP Mon Apr 12 17:18:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- elementary code v3.4.1

**Comment by davidmhewitt** [comment]
See this: https://github.com/mesonbuild/meson/issues/6165

Sounds like you need to install gettext. I'm surprised it wasn't pulled in by the other development dependencies like it is in our CI environments.

**Comment by yonas** [comment]
Thanks, that worked!
